Repository dipdup-io/dipdup, pull requests merged in 2022-03, with the labels that each got.

#249 Rewrite getters for TzKT methods that support pagination
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/index.py
Labels: 🐛 bug, ✨ feature

#198 Prometheus integration
  .github/workflows/build.yml
  CHANGELOG.md
  Dockerfile
  poetry.lock
  pyproject.toml
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/prometheus.py
  src/dipdup/utils/database.py
Labels: ✨ feature

#264 Fix TzKT pagination and Prometheus labels
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/prometheus.py
Labels: 🐛 bug

#268 Remove unused code and unreliable benchmarks
  scripts/commit_benchmarks.sh
  scripts/run_benchmarks.sh
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/test/__init__.py
  src/dipdup/utils/__init__.py
  tests/benchmarks/.gitignore
  tests/benchmarks/add_index.py
  tests/benchmarks/config.py
  tests/benchmarks/index.py
  tests/test_dipdup/__init__.py
  tests/test_dipdup/test_dipdup.py
Labels: 🧹 chore

#266 Fix data loss in `skip_history`, fix default sqlite path
  CHANGELOG.md
  src/dipdup/config.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/index.py
  tests/test_dipdup/test_datasources/test_tzkt/test_datasource.py
Labels: 🐛 bug

#267 User-defined Custom Config
  src/dipdup/config.py
  tests/test_dipdup/test_config/test_custom_config.py
Labels: ✨ feature

#272 Various 5.0 deprecations
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  scripts/init_demos.sh
  src/demo_hic_et_nunc/docker/docker-compose.yml
  src/demo_hic_et_nunc/hooks/on_rollback.py
  src/demo_hic_et_nunc/types/hen_objkts/storage.py
  src/demo_quipuswap/docker/docker-compose.yml
  src/demo_quipuswap/hooks/on_rollback.py
  src/demo_quipuswap/types/fa12_token/storage.py
  src/demo_quipuswap/types/fa2_token/storage.py
  src/demo_registrydao/docker/docker-compose.yml
  src/demo_registrydao/hooks/on_rollback.py
  src/demo_registrydao/types/registry/storage.py
  src/demo_tezos_domains/docker/docker-compose.yml
  src/demo_tezos_domains/hooks/on_rollback.py
  src/demo_tezos_domains_big_map/docker/docker-compose.yml
  src/demo_tezos_domains_big_map/hooks/on_rollback.py
  src/demo_tzbtc/docker/docker-compose.yml
  src/demo_tzbtc/hooks/on_rollback.py
  src/demo_tzbtc/types/tzbtc/storage.py
  src/demo_tzcolors/docker/docker-compose.yml
  src/demo_tzcolors/hooks/on_rollback.py
  src/dipdup/cli.py
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/enums.py
  src/dipdup/exceptions.py
  src/dipdup/index.py
  src/dipdup/migrations.py
  src/dipdup/models.py
  src/dipdup/templates/docker/Dockerfile.j2
  src/dipdup/templates/docker/dipdup.env.j2
  src/dipdup/templates/docker/docker-compose.yml.j2
  src/dipdup/utils/database.py
  tests/integration_tests/test_codegen.py
  tests/integration_tests/test_hasura.py
  tests/test_dipdup/test_context.py
Labels: 🧹 chore

#257 Update internal docs related to DipDup config
  CHANGELOG.md
  CONTRIBUTING.md
  scripts/extract_reference.py
  src/dipdup/cli.py
  src/dipdup/config.py
Labels: 📖 documentation

#274 Fix `TzktDatasource` getters, add missing typehints
  CHANGELOG.md
  poetry.lock
  scripts/extract_reference.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/datasources/subscription.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/exceptions.py
  src/dipdup/models.py
  src/dipdup/prometheus.py
  src/dipdup/utils/__init__.py
  tests/integration_tests/synchronize.py
  tests/integration_tests/test_codegen.py
  tests/integration_tests/test_demos.py
  tests/integration_tests/test_ipfs.py
  tests/integration_tests/test_rollback.py
  tests/test_dipdup/test_config/test_custom_config.py
  tests/test_dipdup/test_context.py
  tests/test_dipdup/test_datasources/test_tzkt/test_datasource.py
  tests/test_dipdup/test_index.py
  tests/test_dipdup/test_introspection.py
  tests/test_dipdup/test_models.py
  tests/test_dipdup/test_utils.py
Labels: 🐛 bug, 🧹 chore
