Repository dipdup-io/dipdup, pull requests merged in 2022-11, with the labels that each got.

#477 Add support for untyped origination indexing
  src/dipdup/config.py
  src/dipdup/index.py
  tests/test_dipdup/test_index.py
Labels: ✨ feature, 👋 community

#513 Bump Hasura and other deps, update contributing guide
  .github/workflows/build.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Makefile
  demos/demo-domains-big-map/docker-compose.swarm.yml
  demos/demo-domains-big-map/docker-compose.yml
  demos/demo-domains-big-map/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-head/src/demo_head/__init__.py
  demos/demo-head/src/demo_head/handlers/on_mainnet_head.py
  demos/demo-head/src/demo_head/hooks/on_index_rollback.py
  demos/demo-head/src/demo_head/hooks/on_reindex.py
  demos/demo-head/src/demo_head/hooks/on_restart.py
  demos/demo-head/src/demo_head/hooks/on_synchronized.py
  demos/demo-head/src/demo_head/models.py
  demos/demo-hic-et-nunc/docker-compose.swarm.yml
  demos/demo-hic-et-nunc/docker-compose.yml
  demos/demo-hic-et-nunc/replay.json
  demos/demo-quipuswap/docker-compose.swarm.yml
  demos/demo-quipuswap/docker-compose.yml
  demos/demo-quipuswap/replay.json
  demos/demo-registrydao/docker-compose.swarm.yml
  demos/demo-registrydao/docker-compose.yml
  demos/demo-registrydao/replay.json
  demos/demo-tzbtc-transfers/docker-compose.swarm.yml
  demos/demo-tzbtc-transfers/docker-compose.yml
  demos/demo-tzbtc-transfers/replay.json
  demos/demo-tzbtc/docker-compose.swarm.yml
  demos/demo-tzbtc/docker-compose.yml
  demos/demo-tzbtc/replay.json
  demos/demo-tzcolors/docker-compose.swarm.yml
  demos/demo-tzcolors/docker-compose.yml
  demos/demo-tzcolors/replay.json
  docs/cookiecutter.json
  docs/examples/built-with-dipdup.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/demo_events
  src/demo_head
  src/dipdup/project.py
Labels: 🧹 chore

#509 Change formatter from black/140 to blue/120, logo in docs
  Makefile
  demos/demo-domains-big-map/src/demo_domains_big_map/handlers/on_update_records.py
  demos/demo-domains/src/demo_domains/handlers/on_storage_diff.py
  docs/book.css
  docs/theme/header.png
  docs/theme/index.hbs
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/datasources/coinbase/datasource.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/datasources/tzkt/enums.py
  src/dipdup/dipdup.py
  src/dipdup/hasura.py
  src/dipdup/index.py
  src/dipdup/install.py
  src/dipdup/models.py
  src/dipdup/project.py
  src/dipdup/scheduler.py
  src/dipdup/utils/database.py
  tests/test_dipdup/test_config/test_custom_config.py
  tests/test_dipdup/test_index.py
  tests/test_dipdup/test_models.py
Labels: 🧹 chore

#523 Fix deserializing `EventData` model
  CHANGELOG.md
  docs/config/reference.md
  src/dipdup/datasources/tzkt/datasource.py
Labels: 🐛 bug

#524 Configure package logger in addition to `dipdup` one
  CHANGELOG.md
  src/dipdup/config.py
Labels: 🐛 bug

#528 Fix crash when using F expressions in versioned transactions
  CHANGELOG.md
  src/dipdup/models.py
  tests/test_dipdup/test_rollback.py
Labels: 🐛 bug, 👋 community

#514 `operation_unfiltered` index release
  CHANGELOG.md
  CONTRIBUTING.md
  docs/config/reference.md
  docs/indexes/big_map.md
  docs/indexes/operation_unfiltered.md
  src/dipdup/__init__.py
  src/dipdup/config.py
  src/dipdup/index.py
  src/dipdup/project.py
Labels: 📖 documentation, 🧹 chore

#526 Filtering token transfers by contract/token_id/standard
  CHANGELOG.md
  demos/demo-tzbtc-transfers/dipdup.yml
  docs/config/reference.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/config.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/datasources/tzkt/enums.py
  src/dipdup/datasources/tzkt/fetcher.py
  src/dipdup/datasources/tzkt/models.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/projects/demo_tzbtc_transfers/dipdup.yml.j2
  tests/integration_tests/test_demos.py
  tests/integration_tests/tzbtc_transfers.yml
  tests/integration_tests/tzbtc_transfers_2.yml
  tests/integration_tests/tzbtc_transfers_3.yml
  tests/integration_tests/tzbtc_transfers_4.yml
Labels: ✨ feature

#385 `execute_sql_query`, configurable `head_status_timeout`
  CHANGELOG.md
  docs/include/context-reference.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/datasources/coinbase/datasource.py
  src/dipdup/datasources/datasource.py
  src/dipdup/datasources/ipfs/datasource.py
  src/dipdup/datasources/metadata/datasource.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/dipdup.py
  src/dipdup/exceptions.py
  src/dipdup/hasura.py
  src/dipdup/http.py
  src/dipdup/sql/dipdup_head_status.sql
  src/dipdup/sql/on_reindex/dipdup_head_status.sql
  src/dipdup/sql/truncate_schema.sql
  src/dipdup/utils/__init__.py
  src/dipdup/utils/database.py
  tests/test_dipdup/test_config.py
  tests/test_dipdup/test_datasources/test_ipfs.py
Labels: 🐛 bug, ✨ feature

#532 Better PEP 8 compatibility of generated callbacks
  CHANGELOG.md
  src/dipdup/codegen.py
  src/dipdup/templates/callback.py.j2
Labels: 🧹 chore, 🧁 improvement

#533 Fix empty contract balance in the `amount` field
  .github/workflows/test.yml
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  tests/test_dipdup/responses/origination_amount.json
  tests/test_dipdup/test_models.py
Labels: 🐛 bug

#537 REVERT: postpone `operation_unfiltered` release
  CHANGELOG.md
  demos/demo-tzbtc-transfers/src/demo_tzbtc_transfers/handlers/on_token_transfer.py
  docs/SUMMARY.md
  docs/config/indexes.md
  docs/config/reference.md
  docs/indexes/operation_unfiltered.md
  docs/indexes/token_transfer.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/config.py
  src/dipdup/index.py
  src/dipdup/projects/demo_tzbtc_transfers/src/{{cookiecutter.package}}/handlers/on_token_transfer.py.j2
  tests/test_index.py
Labels: 🧹 chore

#542 Fix post-release workflow
  .github/workflows/release.yml
Labels: 🚢 ci/cd

#540 Handle untyped originations, fix callback signatures
  CHANGELOG.md
  docs/config/reference.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/datasources/tzkt/models.py
  src/dipdup/index.py
  tests/test_config/test_callbacks.py
Labels: 🐛 bug, 👋 community

#548 Forbid using Hasura instances running vulnerable versions
  CHANGELOG.md
  demos/demo-domains-big-map/docker-compose.swarm.yml
  demos/demo-domains-big-map/docker-compose.yml
  demos/demo-domains-big-map/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-hic-et-nunc/docker-compose.swarm.yml
  demos/demo-hic-et-nunc/docker-compose.yml
  demos/demo-hic-et-nunc/replay.json
  demos/demo-quipuswap/docker-compose.swarm.yml
  demos/demo-quipuswap/docker-compose.yml
  demos/demo-quipuswap/replay.json
  demos/demo-registrydao/docker-compose.swarm.yml
  demos/demo-registrydao/docker-compose.yml
  demos/demo-registrydao/replay.json
  demos/demo-tzbtc-transfers/docker-compose.swarm.yml
  demos/demo-tzbtc-transfers/docker-compose.yml
  demos/demo-tzbtc-transfers/replay.json
  demos/demo-tzbtc/docker-compose.swarm.yml
  demos/demo-tzbtc/docker-compose.yml
  demos/demo-tzbtc/replay.json
  demos/demo-tzcolors/docker-compose.swarm.yml
  demos/demo-tzcolors/docker-compose.yml
  demos/demo-tzcolors/replay.json
  docs/cookiecutter.json
  poetry.lock
  pyproject.toml
  src/dipdup/exceptions.py
  src/dipdup/hasura.py
  src/dipdup/http.py
  src/dipdup/project.py
  tests/test_hasura.py
Labels: 🧨 critical, 🌊 upstream

#549 Set config annotations in runtime to allow unresolved links
  CHANGELOG.md
  docs/config/reference.md
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/datasources/metadata/enums.py
  src/dipdup/index.py
  tests/replays/aa8fe6037996b296bf9a3011e45cd9ecb92fb728592a843f91b03b2848cb1fb1
  tests/replays/c0fda4857a03b944f0d9363fb906fbe3d6c0498c4d53a490a2e08288d1014fd2
  tests/replays/c4a88d324538cb6fdfe70ec3fc6e217c5ee669babeae5caf851d39c0c460d3c0
  tests/test_hasura.py
Labels: 🧹 chore
