Repository dipdup-io/dipdup, pull requests merged in 2022-09, with the labels that each got.

#467 Lock Pydantic; v1.10 breaks our codegen
  .github/workflows/cookiecutter.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Dockerfile
  Makefile
  cookiecutter/README.md
  docs/troubleshooting.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
Labels: 🐛 bug, 🌊 upstream

#479 Remove deprecated block field `priority`
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/models.py
Labels: 🐛 bug, 👋 community, 🧨 critical

#474 Codegen and config validation fixes
  .github/workflows/build.yml
  .github/workflows/cookiecutter.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  docs/assets/operation-bcd.png
  docs/assets/operation-config.png
  docs/book.css
  docs/config/indexes/README.md
  docs/config/indexes/operation.md
  docs/config/reference.md
  docs/faq.md
  docs/theme/index.hbs
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/config.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/exceptions.py
  src/dipdup/http.py
  src/dipdup/utils/database.py
  tests/integration_tests/test_hasura.py
  tests/test_dipdup/test_datasources/test_tzkt.py
Labels: 🐛 bug, 👋 community

#487 Update metadata network aliases
  CHANGELOG.md
  docs/config/datasources.md
  docs/config/reference.md
  docs/release-notes/4.1.0.md
  src/dipdup/config.py
  src/dipdup/datasources/metadata/enums.py
  tests/test_dipdup/test_datasources/test_metadata.py
  tests/test_dipdup/test_datasources/test_tzkt.py
Labels: 🐛 bug, 📖 documentation

#489 Rename `dipdup-py` to `dipdup`
  CHANGELOG.md
  README.md
  cookiecutter/README.md
  cookiecutter/{{cookiecutter.project_name}}/docker-compose.swarm.yml
  docs/cli-reference.md
  docs/deployment/docker.md
  docs/examples/demo-projects.md
  docs/getting-started/installation.md
  docs/troubleshooting.md
  pyproject.toml
  scripts/install.py
  src/dipdup/cli.py
Labels: 🧹 chore, 🚢 ci/cd

#490 Rename tombstones to crashdumps, update path
  CHANGELOG.md
  docs/advanced/feature-flags.md
  docs/release-notes/6.0.0.md
  docs/troubleshooting.md
  src/dipdup/cli.py
  src/dipdup/exceptions.py
Labels: 🧹 chore, 🧁 improvement

#484 Update mdbook docs domains
  .github/workflows/docs.yml
  docs/theme/index.hbs
Labels: 📖 documentation, 🚢 ci/cd

#488 Keep test replays in /tmp
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/config.py
  src/dipdup/http.py
  tests/integration_tests/hic_et_nunc.yml
  tests/integration_tests/quipuswap.yml
  tests/integration_tests/registrydao.yml
  tests/integration_tests/tezos_domains.yml
  tests/integration_tests/tezos_domains_big_map.yml
  tests/integration_tests/tzbtc.yml
  tests/integration_tests/tzbtc_transfers.yml
  tests/integration_tests/tzbtc_transfers_2.yml
  tests/integration_tests/tzbtc_transfers_3.yml
  tests/integration_tests/tzbtc_transfers_4.yml
  tests/integration_tests/tzcolors.yml
  tests/test_dipdup/asdf.yml
  tests/test_dipdup/dipdup.yml
  tests/test_dipdup/hen_subjkt.yml
  tests/test_dipdup/hjkl.yml
  tests/test_dipdup/kolibri_ovens.yml
  tests/test_dipdup/qwer.yml
  tests/test_dipdup/rewq.yml
  tests/test_dipdup/test_datasources/test_tzkt.py
  tests/test_dipdup/yupana.yml
  tests/test_dipdup/zxcv.yml
Labels: 🧹 chore, 🚢 ci/cd

#492 Update docs links, build less nightly images
  .github/workflows/build.yml
  .github/workflows/cookiecutter.yml
  .github/workflows/docs.yml
  .github/workflows/homepage.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CHANGELOG.md
  Makefile
  README.md
  docs/cli-reference.md
  scripts/install.py
  src/dipdup/cli.py
  src/dipdup/exceptions.py
Labels: 📖 documentation, 🚢 ci/cd

#494 Install cookiecutter and poetry globally
  .github/workflows/installer.yml
  scripts/install.py
Labels: 🚢 ci/cd

#496 Docs: article about monitoring endpoints
  docs/SUMMARY.md
  docs/deployment/monitoring.md
Labels: 📖 documentation
