Repository dipdup-io/dipdup, pull requests merged in 2022-07, with the labels that each got.

#410 Fix setting default logging level
  CHANGELOG.md
  src/dipdup/config.py
Labels: 🐛 bug

#409 Fix hasura metadata generation with custom relation source field name
  CHANGELOG.md
  docs/cli-reference.md
  docs/deployment/docker-compose.md
  src/dipdup/hasura.py
  tests/__init__.py
  tests/integration_tests/test_hasura.py
Labels: 🐛 bug

#411 Fix Hasura metadata generation
  CHANGELOG.md
  src/demo_hic_et_nunc/graphql/token.graphql
  src/dipdup/hasura.py
  tests/integration_tests/test_hasura.py
Labels: 🐛 bug, 🧨 critical

#413 Sentry: allow customizing `server_name` and `release` tags
  CHANGELOG.md
  docs/config/reference.md
  src/dipdup/cli.py
  src/dipdup/config.py
Labels: 🧁 improvement

#412 Fix `hasura configure` command crash when models have empty `Meta.table`
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/dipdup.py
  src/dipdup/utils/database.py
Labels: 🐛 bug

#417 Remove secrets from config `__repr__`
  CHANGELOG.md
  src/dipdup/config.py
  tests/test_dipdup/test_config.py
Labels: 🧹 chore

#426 Fix oneshot detection without oneshot_indexes
  CHANGELOG.md
  src/dipdup/config.py
Labels: 🐛 bug, 🧨 critical

#425 Build docs-next for prereleases
  .github/workflows/docs.yml
Labels: 🧹 chore

#429 Fix crash when adding an index with new subscriptions in runtime
  CHANGELOG.md
  src/dipdup/datasources/subscription.py
  src/dipdup/index.py
Labels: 🐛 bug, 🧨 critical

#392 Database-level rollbacks (copy-on-write)
  .github/workflows/build.yml
  CHANGELOG.md
  docs/SUMMARY.md
  docs/advanced/context/reference.md
  docs/cli-reference.md
  docs/config/reference.md
  docs/getting-started/core-concepts.md
  docs/release-notes/5.0.0.md
  docs/release-notes/6.0.0.md
  docs/troubleshooting/common-issues.md
  pyproject.toml
  scripts/print_help.py
  src/demo_hic_et_nunc/hooks/on_index_rollback.py
  src/demo_hic_et_nunc/models.py
  src/demo_quipuswap/hooks/on_index_rollback.py
  src/demo_quipuswap/models.py
  src/demo_registrydao/hooks/on_index_rollback.py
  src/demo_registrydao/models.py
  src/demo_tezos_domains/hooks/on_index_rollback.py
  src/demo_tezos_domains/models.py
  src/demo_tezos_domains_big_map/hooks/on_index_rollback.py
  src/demo_tezos_domains_big_map/models.py
  src/demo_tzbtc/hooks/on_index_rollback.py
  src/demo_tzbtc/models.py
  src/demo_tzbtc_transfers/hooks/on_index_rollback.py
  src/demo_tzbtc_transfers/models.py
  src/demo_tzcolors/hooks/on_index_rollback.py
  src/demo_tzcolors/models.py
  src/dipdup/cli.py
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/context.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/dipdup.py
  src/dipdup/exceptions.py
  src/dipdup/hasura.py
  src/dipdup/index.py
  src/dipdup/models.py
  src/dipdup/scheduler.py
  src/dipdup/transactions.py
  src/dipdup/utils/__init__.py
  src/dipdup/utils/database.py
  tests/test_dipdup/test_rollback.py
  tests/test_dipdup/test_utils.py
Labels: ✨ feature

#437 Stop processing commented config lines
  CHANGELOG.md
  src/dipdup/config.py
  tests/test_dipdup/test_config/test_custom_config.py
Labels: 🐛 bug
