Repository dipdup-io/dipdup, pull requests merged in 2022-06, with the labels that each got.

#372 Fix flakeheaven configuration, lint
  pyproject.toml
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/scheduler.py
  src/dipdup/utils/__init__.py
  tests/integration_tests/test_demos.py
Labels: 🧹 chore

#374 Fix .dockerignore
  .dockerignore
Labels: 🧹 chore

#380 Fix crash when rollback hook is about to be called
  CHANGELOG.md
  src/dipdup/config.py
Labels: 🐛 bug, 🧨 critical

#378 Lazy import dependencies to speed up startup
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/codegen.py
Labels: 🧁 improvement

#382 Pre-release docs refresh
  .github/workflows/docs.yml
  CHANGELOG.md
  README.md
  docs/CHANGELOG.md
  docs/Makefile
  docs/README.md
  docs/SUMMARY.md
  docs/advanced/context/reference.md
  docs/advanced/datasources.md
  docs/advanced/feature-flags.md
  docs/advanced/hooks/default.md
  docs/cli/schema-approve.md
  docs/config/reference.md
  docs/getting-started/core-concepts.md
  docs/getting-started/defining-models.md
  docs/getting-started/implementing-handlers.md
  docs/getting-started/installation.md
  docs/getting-started/project-structure.md
  docs/quickstart.md
  src/dipdup/cli.py
Labels: 📖 documentation

#381 Fix crash with `RuntimeError` after continuous realtime connection loss
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
Labels: 🐛 bug, 🧨 critical

#390 Do not skip integration tests in CI
  src/dipdup/utils/__init__.py
  tests/integration_tests/test_codegen.py
  tests/integration_tests/test_hasura.py
Labels: 🧹 chore

#391 Fix token transfers handling for realtime index status
  src/dipdup/datasources/datasource.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
Labels: 🐛 bug, 🧨 critical

#386 Unified CLI reference, new pages, proofreading
  docs/Makefile
  docs/SUMMARY.md
  docs/advanced/context/README.md
  docs/advanced/context/reference.md
  docs/advanced/hooks/default.md
  docs/advanced/metadata-interface.md
  docs/advanced/performance.md
  docs/advanced/performance/README.md
  docs/advanced/performance/database.md
  docs/advanced/performance/datasources.md
  docs/advanced/performance/time-series.md
  docs/advanced/sql.md
  docs/cli-reference.md
  docs/cli/README.md
  docs/cli/cache-clear.md
  docs/cli/cache-show.md
  docs/cli/config-export.md
  docs/cli/hasura-configure.md
  docs/cli/init.md
  docs/cli/migrate.md
  docs/cli/run.md
  docs/cli/schema-approve.md
  docs/cli/schema-export.md
  docs/cli/schema-init.md
  docs/cli/schema-wipe.md
  docs/cli/status.md
  docs/config/reference.md
  docs/cookbook/caching-models.md
  docs/deployment/backups.md
  docs/deployment/logging.md
  docs/getting-started/core-concepts.md
  docs/getting-started/implementing-handlers.md
  docs/getting-started/installation.md
  docs/getting-started/project-structure.md
  docs/graphql/hasura.md
  docs/quickstart.md
  docs/release-notes/5.0.0.md
  docs/troubleshooting/common-issues.md
  src/dipdup/cli.py
Labels: 📖 documentation

#396 Bump pytezos to 3.5.2
  poetry.lock
  pyproject.toml
Labels: 🧹 chore

#397 Update "Immune tables" page, lint docs after build
  Makefile
  docs/config/database.md
Labels: 📖 documentation, 🧹 chore

#400 Add .md link checker to CI, fix broken links
  Makefile
  docs/Makefile
  docs/getting-started/README.md
  docs/placeholders.md
  docs/quickstart.md
  poetry.lock
  pyproject.toml
Labels: 📖 documentation, 🧹 chore

#312 Hasura config and table customisation improvements
  CHANGELOG.md
  src/dipdup/config.py
  src/dipdup/hasura.py
  tests/integration_tests/test_hasura.py
Labels: 🐛 bug, 👋 community, 🧁 improvement

#384 Deprecate `run` command options
  CHANGELOG.md
  docs/config/reference.md
  src/dipdup/cli.py
Labels: 🧹 chore, 🧁 improvement

#402 Introduce 6.0 deprecations
  CHANGELOG.md
  docs/Makefile
  docs/advanced/datasources.md
  docs/advanced/performance.md
  docs/troubleshooting/common-issues.md
  scripts/print_help.py
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/datasources/coinbase/datasource.py
  src/dipdup/datasources/datasource.py
  src/dipdup/datasources/metadata/datasource.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/hasura.py
  src/dipdup/index.py
  src/dipdup/migrations.py
  src/dipdup/utils/watchdog.py
Labels: 🧹 chore

#405 Bump aiohttp
  poetry.lock
  pyproject.toml
Labels: 🧹 chore
