Repository dipdup-io/dipdup, pull requests merged in 2023-05, with the labels that each got.

#690 Fixed waiting for response indefinitely when IPFS hash is not available
  CHANGELOG.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/config.py
  src/dipdup/datasources/metadata/enums.py
  src/dipdup/http.py
Labels: bug

#672 Python 3.11; now on `next`
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  Dockerfile
  demos/demo-auction/pyproject.toml
  demos/demo-big-maps/pyproject.toml
  demos/demo-dao/pyproject.toml
  demos/demo-dex/pyproject.toml
  demos/demo-domains/pyproject.toml
  demos/demo-events/pyproject.toml
  demos/demo-evm-events/pyproject.toml
  demos/demo-factories/pyproject.toml
  demos/demo-head/pyproject.toml
  demos/demo-nft-marketplace/pyproject.toml
  demos/demo-raw/pyproject.toml
  demos/demo-token-transfers/pyproject.toml
  demos/demo-token/pyproject.toml
  docs/deployment/docker.md
  docs/getting-started/installation.md
  docs/quickstart.md
  docs/troubleshooting.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/install.py
  src/dipdup/projects/linters_default/pyproject.toml.j2
  src/dipdup/projects/linters_none/pyproject.toml.j2
Labels: improvement, ci/cd

#689 Move installer commands to `self` group; remove alias
  CHANGELOG.md
  pyproject.toml
  src/dipdup/cli.py
  src/dipdup/install.py
  src/dipdup/models/tzip_metadata.py
Labels: improvement

#700 Bump datamodel-codegen and Hasura
  CHANGELOG.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cli-reference.md
  docs/config/reference.md
  docs/cookiecutter.json
  docs/include/context-reference.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/project.py
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
Labels: chore

#701 Retry aiohttp requests on asyncio.TimeoutError
  CHANGELOG.md
  README.md
  src/dipdup/http.py
Labels: bug

#705 Various 6.5 backports
  CHANGELOG.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/config/reference.md
  docs/cookiecutter.json
  docs/deployment/database-engines.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/models.py
  src/dipdup/project.py
  src/dipdup/transactions.py
  src/dipdup/utils/database.py
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
  tests/test_rollback.py
Labels: bug

#708 Bump version 6.5.7
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
Labels: chore

#697 Make advanced config accept any options
  src/dipdup/config/__init__.py
Labels: chore

#696 Advanced logging level configuration in config
  CHANGELOG.md
  dipdup.yml
  docs/cli-reference.md
  docs/config-reference.rst
  docs/config/logging.md
  docs/config/reference.md
  docs/deployment/logging.md
  docs/include/context-reference.md
  docs/include/dipdup-full.yml
  docs/troubleshooting.md
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_tzkt_token_transfers.py
  src/dipdup/models/__init__.py
  src/dipdup/yaml.py
  tests/configs/demo_auction.yml
  tests/configs/demo_big_maps.yml
  tests/configs/demo_dex.yml
  tests/configs/demo_domains.yml
  tests/configs/demo_nft_marketplace.yml
  tests/configs/demo_token.yml
  tests/configs/demo_token_transfers.yml
  tests/configs/demo_token_transfers_2.yml
  tests/configs/demo_token_transfers_3.yml
  tests/configs/demo_token_transfers_4.yml
Labels: feature
