Repository dipdup-io/dipdup, pull requests merged in 2023-03, with the labels that each got.

#615 Fix Sentry integration bugs
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/sentry.py
Labels: bug

#611 Replace flakeheaven with ruff
  CONTRIBUTING.md
  Makefile
  demos/demo-auction/Makefile
  demos/demo-auction/pyproject.toml
  demos/demo-auction/src/demo_auction/handlers/on_create_auction.py
  demos/demo-big-maps/Makefile
  demos/demo-big-maps/pyproject.toml
  demos/demo-dao/Makefile
  demos/demo-dao/pyproject.toml
  demos/demo-dex/Makefile
  demos/demo-dex/pyproject.toml
  demos/demo-domains/Makefile
  demos/demo-domains/pyproject.toml
  demos/demo-events/Makefile
  demos/demo-events/pyproject.toml
  demos/demo-factories/Makefile
  demos/demo-factories/pyproject.toml
  demos/demo-head/Makefile
  demos/demo-head/pyproject.toml
  demos/demo-nft-marketplace/Makefile
  demos/demo-nft-marketplace/pyproject.toml
  demos/demo-raw/Makefile
  demos/demo-raw/pyproject.toml
  demos/demo-token-transfers/Makefile
  demos/demo-token-transfers/pyproject.toml
  demos/demo-token/Makefile
  demos/demo-token/pyproject.toml
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/exceptions.py
  src/dipdup/project.py
  src/dipdup/projects/demo_auction/src/{{cookiecutter.package}}/handlers/on_create_auction.py.j2
  src/dipdup/projects/linters_advanced/Makefile.j2
  src/dipdup/projects/linters_advanced/pyproject.toml.j2
  src/dipdup/projects/linters_default/Makefile.j2
  src/dipdup/projects/linters_default/pyproject.toml.j2
  tests/test_config/test_callbacks.py
  tests/test_rollback.py
Labels: chore, ci/cd

#617 Announce Alpine image deprecation
  CHANGELOG.md
  docs/deployment/docker.md
  src/dipdup/cli.py
Labels: documentation, ci/cd

#619 Bump Pydantic to fix mypy plugin
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  scripts/update_cookiecutter.py
  scripts/update_demos.py
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/datasources/tzkt/models.py
  src/dipdup/transactions.py
  tests/test_hasura.py
  tests/test_index/test_operation.py
Labels: chore

#629 TokenTransferIndexConfig resolving fixed
  CHANGELOG.md
  src/dipdup/config.py
  tests/configs/demo_token_transfers_4.yml
  tests/test_demos.py
Labels: bug, community

#631 Fix pipelines on `next`
  .github/workflows/installer.yml
  .gitignore
  src/dipdup/config/__init__.py
  tests/configs/demo_token_transfers_4.yml
  tests/replays/9ce1bc12a2adeddcf9d8854c4b63a8e65b58d9206fb8d2e3eedb24c44ea7f28a
Labels: chore

#632 Forbid using Hasura instances affected by GHSA-c9rw-rw2f-mj4x
  .gitignore
  CHANGELOG.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cookiecutter.json
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/hasura.py
  src/dipdup/project.py
  tests/replays/9ce1bc12a2adeddcf9d8854c4b63a8e65b58d9206fb8d2e3eedb24c44ea7f28a
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
Labels: bug, upstream

#633 Disable logging of DeprecationWarnings and BrokenPipeErrors
  CHANGELOG.md
  docs/cli-reference.md
  src/dipdup/cli.py
  src/dipdup/utils/sys.py
Labels: bug

#637 Fix `from_` field alias in token transfer handler
  CHANGELOG.md
  src/dipdup/config.py
  src/dipdup/yaml.py
Labels: bug

#638 Update pytezos to 3.9.0
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
Labels: chore

#642 Bump version 6.5.4
  CHANGELOG.md
  docs/config/reference.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.txt
Labels: chore
