Repository dipdup-io/dipdup, pull requests merged in 2023-11, with the labels that each got.

#882 Update default Docker tag for TimescaleDB HA
  CHANGELOG.md
  src/demo_uniswap/configs/replay.yaml
  src/demo_uniswap/deploy/compose.swarm.yaml
  src/demo_uniswap/deploy/compose.yaml
  src/dipdup/project.py
  src/dipdup/projects/demo_uniswap/replay.yaml
Labels: bug

#885 Fix crash on early Python 3.11 releases
  CHANGELOG.md
  docs/15.thanks.md
  src/dipdup/cli.py
Labels: bug

#886 Fix typos in docs
  docs/1.getting-started/3.config.md
  docs/6.deployment/4.prometheus.md
  docs/7.references/4.config-details.md
  docs/9.release-notes/4.history.md
  src/dipdup/exceptions.py
Labels: documentation, community

#888 Bump version 7.1.1
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/models/repo.py
  src/demo_uniswap/pyproject.toml
  src/dipdup/performance.py
  src/dipdup/projects/demo_uniswap/models/repo.py.j2
Labels: ci/cd

#889 Update thanks page
  docs/15.thanks.md
Labels: documentation

#875 Refactor TzKT indexes
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_events/index.py
  src/dipdup/indexes/tezos_tzkt_head/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_token_balances/index.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
Labels: chore

#892 Add Prometheus metrics for subsquid cloud
  CHANGELOG.md
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/http.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/prometheus.py
Labels: feature

#887 Batch requesting logs from EVM node
  CHANGELOG.md
  src/dipdup/indexes/evm_subsquid_events/index.py
Labels: improvement

#895 Update PyArrow to 14.0.1
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/datasources/evm_node.py
  src/dipdup/hasura.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
Labels: bug, upstream

#899 Add ignore_missing to getsentry/action-release
  .github/workflows/release.yml
Labels: ci/cd

#898 Don't suppress uncaught exceptions when performance monitoring is disabled
  CHANGELOG.md
  src/dipdup/cli.py
Labels: bug

#894 Etherlink support
  CHANGELOG.md
  docs/2.indexes/5.tezos_tzkt_operations.md
  docs/9.release-notes/_v7.2.md
  src/demo_etherlink/.dockerignore
  src/demo_etherlink/.gitignore
  src/demo_etherlink/README.md
  src/demo_etherlink/__init__.py
  src/demo_etherlink/abi/.keep
  src/demo_etherlink/configs/.keep
  src/demo_etherlink/configs/dipdup.compose.yaml
  src/demo_etherlink/configs/dipdup.sqlite.yaml
  src/demo_etherlink/configs/dipdup.swarm.yaml
  src/demo_etherlink/configs/replay.yaml
  src/demo_etherlink/deploy/.env.default
  src/demo_etherlink/deploy/.keep
  src/demo_etherlink/deploy/Dockerfile
  src/demo_etherlink/deploy/compose.sqlite.yaml
  src/demo_etherlink/deploy/compose.swarm.yaml
  src/demo_etherlink/deploy/compose.yaml
  src/demo_etherlink/deploy/sqlite.env.default
  src/demo_etherlink/deploy/swarm.env.default
  src/demo_etherlink/dipdup.yaml
  src/demo_etherlink/graphql/.keep
  src/demo_etherlink/handlers/.keep
  src/demo_etherlink/handlers/on_rollup_call.py
  src/demo_etherlink/hasura/.keep
  src/demo_etherlink/hooks/.keep
  src/demo_etherlink/hooks/on_index_rollback.py
  src/demo_etherlink/hooks/on_reindex.py
  src/demo_etherlink/hooks/on_restart.py
  src/demo_etherlink/hooks/on_synchronized.py
  src/demo_etherlink/models/.keep
  src/demo_etherlink/models/__init__.py
  src/demo_etherlink/py.typed
  src/demo_etherlink/pyproject.toml
  src/demo_etherlink/sql/.keep
  src/demo_etherlink/sql/on_index_rollback/.keep
  src/demo_etherlink/sql/on_reindex/.keep
  src/demo_etherlink/sql/on_restart/.keep
  src/demo_etherlink/sql/on_synchronized/.keep
  src/demo_etherlink/types/.keep
  src/demo_etherlink/types/controller/tezos_parameters/default.py
  src/demo_etherlink/types/controller/tezos_storage.py
  src/demo_etherlink/types/rollup/tezos_parameters/default.py
  src/demo_etherlink/types/rollup/tezos_storage.py
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/config/tezos.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/project.py
  src/dipdup/projects/demo_etherlink/dipdup.yaml.j2
  src/dipdup/projects/demo_etherlink/handlers/on_rollup_call.py.j2
  src/dipdup/projects/demo_etherlink/replay.yaml
  tests/configs/demo_etherlink.yaml
  tests/test_demos.py
Labels: feature

#902 Refactor metrics
  docs/6.deployment/4.prometheus.md
  docs/7.references/2.config.md
  src/dipdup/config/__init__.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_events/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
  src/dipdup/performance.py
  src/dipdup/prometheus.py
Labels: improvement

#904 Fixed an issue with realtime subscriptions which led to indexing being stuck in some cases
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/config/__init__.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/http.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/sentry.py
Labels: bug
