Repository dipdup-io/dipdup, pull requests merged in 2023-07, with the labels that each got.

#728 Fix watch_docs script
  Makefile
  docs/1.getting-started/1.installation.md
  docs/1.getting-started/3.config.md
  docs/1.getting-started/4.structure.md
  docs/1.getting-started/5.models.md
  docs/1.getting-started/7.env-variables.md
  docs/2.indexes/1.indexes.md
  docs/2.indexes/2.tezos_tzkt_big_maps.md
  docs/2.indexes/3.tezos_tzkt_events.md
  docs/2.indexes/4.tezos_tzkt_head.md
  docs/2.indexes/7.tezos_tzkt_token_transfers.md
  docs/4.graphql/2.hasura.md
  docs/4.graphql/3.rest.md
  docs/4.graphql/4.genql.md
  docs/5.advanced/1.datasources.md
  docs/5.advanced/10.performance.md
  docs/5.advanced/11.sql.md
  docs/5.advanced/2.hooks.md
  docs/5.advanced/3.system-hooks.md
  docs/5.advanced/7.index-factories.md
  docs/5.advanced/9.metadata-interface.md
  docs/6.deployment/1.database.md
  docs/6.deployment/2.docker.md
  docs/6.deployment/7.monitoring.md
  docs/9.config/0.config.md
  docs/9.config/1.advanced.md
  docs/9.config/13.sentry.md
  docs/9.config/5.datasources.md
  docs/9.config/6.hasura.md
  docs/9.config/7.hooks.md
  docs/Makefile
  docs/faq.md
  docs/include/config-toc.md
  docs/placeholders.md
  docs/quickstart.md
  docs/release-notes/4.1.0.md
  docs/release-notes/5.0.0.md
  docs/release-notes/5.1.0.md
  docs/release-notes/6.0.0.md
  docs/release-notes/6.2.0.md
  docs/release-notes/7.0.0.md
  docs/troubleshooting.md
  scripts/update_project.py
  scripts/watch_docs.py
  src/dipdup/project.py
Labels: documentation, ci/cd

#730 Add survey for prompts
  scripts/docs.py
  src/dipdup/project.py
Labels: feature

#732 Transactions fullscan fix
  src/dipdup/datasources/tzkt/datasource.py
Labels: bug

#737 Add support for pyenv and venvs in install script
  src/dipdup/install.py
Labels: bug

#738 Debian 12 images
  CHANGELOG.md
  Dockerfile
  docs/6.deployment/2.docker.md
Labels: ci/cd

#739 Add links to installer and CLI root
  src/dipdup/cli.py
  src/dipdup/install.py
Labels: improvement

#742 Update package metadata, fix models codegen
  docs/1.getting-started/1.installation.md
  docs/1.getting-started/2.core-concepts.md
  docs/1.getting-started/4.package.md
  docs/1.getting-started/5.models.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/README.md
  src/demo_big_maps/README.md
  src/demo_blank/README.md
  src/demo_blank/models/__init__.py
  src/demo_dao/README.md
  src/demo_dex/README.md
  src/demo_domains/README.md
  src/demo_events/README.md
  src/demo_events/models/__init__.py
  src/demo_evm_events/README.md
  src/demo_factories/README.md
  src/demo_head/README.md
  src/demo_head/models/__init__.py
  src/demo_nft_marketplace/README.md
  src/demo_raw/README.md
  src/demo_token/README.md
  src/demo_token_transfers/README.md
  src/demo_uniswap/README.md
  src/demo_uniswap/models/position.py
  src/demo_uniswap/models/token.py
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/package.py
  src/dipdup/projects/base/README.md.j2
  src/dipdup/projects/demo_uniswap/models/position.py.j2
  src/dipdup/projects/demo_uniswap/models/token.py.j2
  src/dipdup/templates/models.py
Labels: bug, documentation

#745 Docs: fix build filter, update push branch
  .github/workflows/docs.yml
  docs/1.getting-started/2.core-concepts.md
  scripts/docs.py
Labels: bug, documentation

#746 Fix some broken links
  README.md
  docs/7.references/1.cli.md
  pyproject.toml
  src/demo_auction/README.md
  src/demo_big_maps/README.md
  src/demo_blank/README.md
  src/demo_dao/README.md
  src/demo_dex/README.md
  src/demo_domains/README.md
  src/demo_events/README.md
  src/demo_evm_events/README.md
  src/demo_factories/README.md
  src/demo_head/README.md
  src/demo_nft_marketplace/README.md
  src/demo_raw/README.md
  src/demo_token/README.md
  src/demo_token_transfers/README.md
  src/demo_uniswap/README.md
  src/dipdup/exceptions.py
  src/dipdup/install.py
  src/dipdup/projects/base/README.md.j2
  src/dipdup/yaml.py
Labels: bug, documentation

#747 Minor documentation and CI improvements
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  docs/0.quickstart.md
  docs/1.getting-started/4.package.md
  docs/1.getting-started/8.handlers.md
  docs/12.faq.md
  docs/13.contributing.md
  docs/14.troubleshooting.md
  docs/15.license.md
  docs/15.opensource.md
  docs/2.indexes/2.tezos_tzkt_big_maps.md
  docs/2.indexes/3.tezos_tzkt_events.md
  docs/4.graphql/1.overview.md
  docs/5.advanced/4.metadata-interface.md
  docs/6.deployment/1.database.md
  docs/6.deployment/4.prometheus.md
  docs/9.release-notes/2.v6.2.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
Labels: documentation, ci/cd

#749 Add missing datasource headers
  docs/3.datasources/1.abi_etherscan.md
  docs/3.datasources/2.coinbase.md
  docs/3.datasources/3.evm_node.md
  docs/3.datasources/5.http.md
  docs/3.datasources/6.ipfs.md
  docs/3.datasources/7.tezos_tzkt.md
  docs/3.datasources/8.tzip_metadata.md
  docs/5.advanced/4.metadata-interface.md
Labels: documentation

#753 Release 7.0.0rc2
  CHANGELOG.md
  docs/9.release-notes/1.v7.0.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/install.py
Labels: chore

#755 Remove Python limitation on large int<->str conversions
  CHANGELOG.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/datasources/tzkt/datasource.py
Labels: bug

#756 Remove Python limitation on large int<->str conversions (next)
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/models/tezos_tzkt.py
Labels: bug
