Repository dipdup-io/dipdup, pull requests merged in 2023-01, with the labels that each got.

#582 Fix Sentry crash reports, increase message limit
  CHANGELOG.md
  docs/cli-reference.md
  docs/config/reference.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  src/demo-auction
  src/demo-big-maps
  src/demo-dao
  src/demo-dex
  src/demo-domains
  src/demo-events
  src/demo-factories
  src/demo-head
  src/demo-nft-marketplace
  src/demo-token
  src/demo-token-transfers
  src/dipdup/cli.py
  src/dipdup/config.py
  src/dipdup/exceptions.py
  src/dipdup/sentry.py
  tests/replays/377ac31d6316391ed138df44bec374d65202f0577603e80465ced3c09140f78c
  tests/replays/76d49ae3b723376c88ca65a3080a273e098d226932a1a49c38fbc4421e7c2e64
  tests/replays/aa8fe6037996b296bf9a3011e45cd9ecb92fb728592a843f91b03b2848cb1fb1
  tests/replays/d0a594d14bcb3fbf916092ec6707dfd3c9f48f53f0a1ad40a32023e7a87f8ef5
Labels: bug, critical

#586 Fix `ctx.add_contract` arguments and complex transaction matching
  CHANGELOG.md
  Makefile
  docs/include/context-reference.md
  poetry.lock
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/context.py
  src/dipdup/datasources/datasource.py
  src/dipdup/indexes/operation/index.py
  src/dipdup/indexes/operation/matcher.py
  tests/test_context.py
Labels: bug, community

#591 Arbitrary hasura metadata customisations
  src/dipdup/codegen.py
  src/dipdup/hasura.py
Labels: feature, community

#588 Split YAML processing to separate module
  src/dipdup/config.py
  src/dipdup/utils/__init__.py
  src/dipdup/yaml.py
Labels: chore

#589 Fix crash when schema generation should fail with `schema_modified`
  CHANGELOG.md
  src/dipdup/dipdup.py
Labels: bug, community

#590 Flush and reopen Sentry session daily
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/sentry.py
Labels: chore

#597 Document internal env variables; update ctx reference and feature flags page
  docs/Makefile
  docs/advanced/feature-flags.md
  docs/context-reference.rst
  docs/getting-started/project-structure.md
  docs/graphql/README.md
  docs/include/context-reference.md
  src/dipdup/context.py
Labels: documentation

#599 Hasura custom metadata docs
  docs/graphql/hasura.md
Labels: documentation, feature, community

#598 Improve config and context reference pages
  docs/book.css
  docs/conf.py
  docs/config-reference.rst
  docs/config/reference.md
  docs/include/context-reference.md
Labels: documentation
