Repository dipdup-io/dipdup, pull requests merged in 2023-04, with the labels that each got.

#639 Request plain values instead of mappings from TzKT
  CHANGELOG.md
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  tests/test_datasources/__init__.py
  tests/test_datasources/test_tzkt.py
Labels: feature

#654 (2/2) Introduce spec_version 2.0
  src/dipdup/__init__.py
  src/dipdup/cli.py
  src/dipdup/exceptions.py
  src/dipdup/project.py
  src/dipdup/yaml.py
Labels: documentation, chore

#655 Enable early realtime mode when config contains bigmap indexes with `skip_history`
  CHANGELOG.md
  src/dipdup/config.py
Labels: bug

#651 Fix crash when using custom datasources
  CHANGELOG.md
  src/dipdup/datasources/datasource.py
  src/dipdup/http.py
Labels: bug, community

#652 Bump Hasura to 2.22.1
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cookiecutter.json
  src/dipdup/project.py
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
Labels: chore

#670 Allow mixing `source` and `entrypoint` filters in `operation` index pattern
  CHANGELOG.md
  src/dipdup/config.py
Labels: improvement

#659 Bump version 6.5.5
  .github/workflows/installer.yml
  CHANGELOG.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-big-maps/src/demo_big_maps/handlers/on_update_records.py
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-domains/src/demo_domains/handlers/on_storage_diff.py
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cookiecutter.json
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/codegen.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/project.py
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
Labels: ci/cd

#624 (1/2) Introduce spec_version 2.0
  demos/demo-auction/dipdup.yml
  demos/demo-big-maps/dipdup.yml
  demos/demo-dao/dipdup.yml
  demos/demo-dex/dipdup.yml
  demos/demo-domains/dipdup.yml
  demos/demo-events/dipdup.yml
  demos/demo-evm-events/dipdup.yml
  demos/demo-factories/dipdup.yml
  demos/demo-head/dipdup.yml
  demos/demo-nft-marketplace/dipdup.yml
  demos/demo-raw/dipdup.yml
  demos/demo-token-transfers/dipdup.yml
  demos/demo-token/dipdup.yml
  docs/config/reference.md
  docs/config/spec_version.md
  docs/include/dipdup-full.yml
  src/dipdup/__init__.py
  src/dipdup/cli.py
  src/dipdup/config/__init__.py
  src/dipdup/exceptions.py
  src/dipdup/project.py
  src/dipdup/projects/blank/dipdup.yml.j2
  src/dipdup/projects/demo_auction/dipdup.yml.j2
  src/dipdup/projects/demo_big_maps/dipdup.yml.j2
  src/dipdup/projects/demo_dao/dipdup.yml.j2
  src/dipdup/projects/demo_dex/dipdup.yml.j2
  src/dipdup/projects/demo_domains/dipdup.yml.j2
  src/dipdup/projects/demo_events/dipdup.yml.j2
  src/dipdup/projects/demo_evm_events/dipdup.yml.j2
  src/dipdup/projects/demo_factories/dipdup.yml.j2
  src/dipdup/projects/demo_head/dipdup.yml.j2
  src/dipdup/projects/demo_nft_marketplace/dipdup.yml.j2
  src/dipdup/projects/demo_raw/dipdup.yml.j2
  src/dipdup/projects/demo_token/dipdup.yml.j2
  src/dipdup/projects/demo_token_transfers/dipdup.yml.j2
  src/dipdup/yaml.py
  tests/configs/asdf.yml
  tests/configs/demo_auction.yml
  tests/configs/demo_big_maps.yml
  tests/configs/demo_dao.yml
  tests/configs/demo_dex.yml
  tests/configs/demo_domains.yml
  tests/configs/demo_factories.yml
  tests/configs/demo_nft_marketplace.yml
  tests/configs/demo_raw.yml
  tests/configs/demo_token.yml
  tests/configs/demo_token_transfers.yml
  tests/configs/demo_token_transfers_2.yml
  tests/configs/demo_token_transfers_3.yml
  tests/configs/demo_token_transfers_4.yml
  tests/configs/dipdup.yml
  tests/configs/hen_subjkt.yml
  tests/configs/hjkl.yml
  tests/configs/kolibri_ovens.yml
  tests/configs/operation_filters.yml
  tests/configs/qwer.yml
  tests/configs/rewq.yml
  tests/configs/yupana.yml
  tests/configs/zxcv.yml
  tests/test_rollback.py
Labels: documentation, feature

#674 Add sponsors and contributors to README.md
  README.md
Labels: documentation, community

#671 Merge 6.5.5 to `next`
  .github/workflows/installer.yml
  CHANGELOG.md
  README.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-big-maps/src/demo_big_maps/handlers/on_update_records.py
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-domains/src/demo_domains/handlers/on_storage_diff.py
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cookiecutter.json
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/codegen/__init__.py
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_tzkt_operations.py
  src/dipdup/datasources/__init__.py
  src/dipdup/http.py
  src/dipdup/project.py
  src/dipdup/yaml.py
  tests/replays/9de859083ed1dd278893f60b5a60feab02a04637327a664af23f52dabb139fe6
Labels: ci/cd

#684 Bump dependencies on 6.5
  CHANGELOG.md
  Dockerfile.slim
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
Labels: chore
