Repository dipdup-io/dipdup, pull requests merged in 2023-09, with the labels that each got.

#825 Fix parsing block timestamp
  pyproject.toml
  src/dipdup/datasources/evm_node.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  tests/configs/demo_evm_events.yml
  tests/test_demos.py
  tests/test_models.py
  tests/test_rollback.py
Labels: bug

#827 Sync to `last_level` if specified in config
  CHANGELOG.md
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  tests/test_demos.py
Labels: bug

#828 Switch installer to rc5
  src/dipdup/install.py
Labels: ci/cd

#813 Fix operations matcher empty parameter check
  CHANGELOG.md
  docs/13.troubleshooting.md
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
  src/dipdup/utils.py
  tests/test_utils.py
Labels: bug

#831 Fix issue with processing rollbacks while sync is in progress
  CHANGELOG.md
  src/dipdup/context.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_events/index.py
  src/dipdup/indexes/tezos_tzkt_head/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
  src/dipdup/models/tezos_tzkt.py
Labels: bug

#832 Backport: Fix issue with processing rollbacks while sync is in progress
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/indexes/big_map/index.py
  src/dipdup/indexes/event/index.py
  src/dipdup/indexes/head/index.py
  src/dipdup/indexes/operation/index.py
  src/dipdup/indexes/token_transfer/index.py
  src/dipdup/models.py
Labels: bug

#835 Backport: Fixed parsing TzKT contract event data
  demos/demo-events/dipdup.yml
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/models.py
  src/dipdup/projects/demo_events/dipdup.yml.j2
Labels: bug

#807 Fix operation matching when contract code hash specified as a string
  CHANGELOG.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
  src/demo_factories/dipdup.yaml
  src/demo_factories/handlers/on_factory_origination.py
  src/demo_factories/handlers/on_origination.py
  src/demo_factories/handlers/on_propose.py
  src/demo_factories/handlers/on_transfer.py
  src/demo_factories/models/__init__.py
  src/demo_factories/types/factory/tezos_storage.py
  src/demo_factories/types/registry/tezos_parameters/propose.py
  src/demo_factories/types/registry/tezos_storage.py
  src/demo_factories/types/token/tezos_parameters/transfer.py
  src/demo_factories/types/token/tezos_storage.py
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos.py
  src/dipdup/context.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
  src/dipdup/projects/demo_factories/dipdup.yaml.j2
  src/dipdup/projects/demo_factories/handlers/on_factory_origination.py.j2
  src/dipdup/projects/demo_factories/handlers/on_origination.py.j2
  src/dipdup/projects/demo_factories/handlers/on_propose.py.j2
  src/dipdup/projects/demo_factories/handlers/on_transfer.py.j2
  src/dipdup/projects/demo_factories/models/__init__.py.j2
  tests/configs/demo_factories.yml
  tests/test_demos.py
  tests/test_index/test_tzkt_operations.py
Labels: bug

#836 6.5.12 release
  CHANGELOG.md
  docs/theme/index.hbs
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/cli.py
Labels: ci/cd

#839 Include rendered demo projects in Docker image
  .dockerignore
  Dockerfile
  docs/8.examples/1.demos.md
Labels: improvement

#838 Fix parsing topics and integers in evm.mode models
  CHANGELOG.md
  docs/15.thanks.md
  src/dipdup/datasources/evm_node.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/models/evm_node.py
  src/dipdup/models/evm_subsquid.py
Labels: bug

#840 Fix incorrect log request parameters
  CHANGELOG.md
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/models/evm_subsquid.py
Labels: bug

#814 Uniswap demo fixes
  src/demo_factories/dipdup.yaml
  src/demo_uniswap/dipdup.yaml
  src/demo_uniswap/handlers/factory/pool_created.py
  src/demo_uniswap/handlers/pool/swap.py
  src/demo_uniswap/handlers/position_manager/collect.py
  src/demo_uniswap/handlers/position_manager/decrease_liquidity.py
  src/demo_uniswap/handlers/position_manager/increase_liquidity.py
  src/demo_uniswap/handlers/position_manager/transfer.py
  src/demo_uniswap/models/pool.py
  src/demo_uniswap/models/position.py
  src/demo_uniswap/models/tick.py
  src/demo_uniswap/models/token.py
  src/demo_uniswap/sql/on_reindex/00_prepare_db.sql
  src/demo_uniswap/sql/on_reindex/01_create_mv_token_price.sql
  src/demo_uniswap/sql/on_reindex/10_create_mv_quotes_1m.sql
  src/demo_uniswap/sql/on_reindex/11_create_mv_quotes_1d.sql
  src/demo_uniswap/sql/on_reindex/20_create_ca_quotes_1m.sql
  src/demo_uniswap/sql/on_reindex/21_create_ca_quotes_1d.sql
  src/dipdup/projects/demo_uniswap/dipdup.yaml.j2
  src/dipdup/projects/demo_uniswap/handlers/factory/pool_created.py.j2
  src/dipdup/projects/demo_uniswap/handlers/pool/burn.py.j2
  src/dipdup/projects/demo_uniswap/handlers/pool/flash.py.j2
  src/dipdup/projects/demo_uniswap/handlers/pool/initialize.py.j2
  src/dipdup/projects/demo_uniswap/handlers/pool/mint.py.j2
  src/dipdup/projects/demo_uniswap/handlers/pool/swap.py.j2
  src/dipdup/projects/demo_uniswap/handlers/position_manager/collect.py.j2
  src/dipdup/projects/demo_uniswap/handlers/position_manager/decrease_liquidity.py.j2
  src/dipdup/projects/demo_uniswap/handlers/position_manager/increase_liquidity.py.j2
  src/dipdup/projects/demo_uniswap/handlers/position_manager/transfer.py.j2
  src/dipdup/projects/demo_uniswap/models/__init__.py.j2
  src/dipdup/projects/demo_uniswap/models/abi.py.j2
  src/dipdup/projects/demo_uniswap/models/pool.py.j2
  src/dipdup/projects/demo_uniswap/models/position.py.j2
  src/dipdup/projects/demo_uniswap/models/repo.py.j2
  src/dipdup/projects/demo_uniswap/models/tick.py.j2
  src/dipdup/projects/demo_uniswap/models/token.py.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/00_prepare_db.sql.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/01_create_mv_token_price.sql.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/10_create_mv_quotes_1m.sql.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/11_create_mv_quotes_1d.sql.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/20_create_ca_quotes_1m.sql.j2
  src/dipdup/projects/demo_uniswap/sql/on_reindex/21_create_ca_quotes_1d.sql.j2
  tests/test_demos.py
  tests/test_models.py
  tests/test_rollback.py
Labels: ci/cd

#842 Ask function in install script fix
  CHANGELOG.md
  src/dipdup/install.py
Labels: bug

#843 Fix EvmNodeHeadData model
  pdm.lock
  requirements.dev.txt
  requirements.txt
  src/dipdup/models/evm_node.py
  tests/test_demos.py
  tests/test_models.py
  tests/test_rollback.py
Labels: bug

#841 Backport: install script improvments
  src/dipdup/cli.py
  src/dipdup/install.py
Labels: chore, improvement

#844 Temporarily remove Infura from demos
  docs/3.datasources/3.evm_node.md
  docs/3.datasources/4.evm_subsquid.md
  src/demo_evm_events/deploy/.env.default
  src/demo_evm_events/deploy/sqlite.env.default
  src/demo_evm_events/deploy/swarm.env.default
  src/demo_evm_events/dipdup.yaml
  src/demo_uniswap/deploy/.env.default
  src/demo_uniswap/deploy/sqlite.env.default
  src/demo_uniswap/deploy/swarm.env.default
  src/demo_uniswap/dipdup.yaml
  src/dipdup/projects/demo_evm_events/dipdup.yaml.j2
  src/dipdup/projects/demo_uniswap/dipdup.yaml.j2
  tests/configs/demo_evm_events.yml
Labels: bug

#854 Fixed node log request, decimals in uniswap demo
  CHANGELOG.md
  src/demo_uniswap/models/__init__.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/projects/demo_uniswap/models/__init__.py.j2
Labels: bug

#856 Fix issue with determining the last level when syncing with node
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/env.py
  src/dipdup/http.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  tests/configs/demo_evm_events_node.yml
  tests/test_demos.py
Labels: bug

#858 Warn about unusual paths in timescaledb-ha image
  CHANGELOG.md
  docs/6.deployment/1.database.md
  src/dipdup/project.py
Labels: documentation, improvement

#857 Increase initial Hasura connection retry count
  CHANGELOG.md
  src/dipdup/hasura.py
Labels: bug

#859 Bump version 7.0.1
  CHANGELOG.md
  docs/9.release-notes/1.v7.0.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
Labels: ci/cd

#860 Update 7.0 release notes
  docs/9.release-notes/1.v7.0.md
  docs/9.release-notes/2.v6.2.md
Labels: documentation
