Repository dipdup-io/dipdup, pull requests merged in 2023-10, with the labels that each got.

#852 Update functions to manage database schema
  CHANGELOG.md
  docs/5.advanced/1.reindexing.md
  docs/5.advanced/3.sql.md
  docs/5.advanced/6.sql.md
  src/dipdup/cli.py
  src/dipdup/database.py
  src/dipdup/sql/dipdup_approve.sql
  src/dipdup/sql/dipdup_wipe.sql
  tests/test_demos.py
Labels: bug, feature

#865 TzktDatasource get_transactions() fix
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
Labels: bug, critical

#866 TzKT fix: add changelog, replace ge with gt
  CHANGELOG.md
  src/dipdup/datasources/tezos_tzkt.py
Labels: chore

#867 Fix regression in `get_transactions` method pagination
  CHANGELOG.md
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/indexes/operation/matcher.py
Labels: bug

#868 Bump version 6.5.13
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/datasources/tzkt/models.py
  src/dipdup/scheduler.py
  src/dipdup/utils/database.py
  tests/test_hasura.py
Labels: ci/cd

#869 Bump version 7.0.2
  .github/workflows/docs.yml
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/dump_schema.py
  src/demo_uniswap/models/repo.py
  src/dipdup/database.py
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/indexes/tezos_tzkt_operations/parser.py
  src/dipdup/performance.py
  src/dipdup/project.py
  src/dipdup/projects/demo_uniswap/models/repo.py.j2
  src/dipdup/scheduler.py
  tests/profile_abi_decoding.py
  tests/test_hasura.py
  tests/test_introspection.py
Labels: ci/cd

#874 Update actions; don't lock dependencies in CI
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ci/cd

#864 Helpers for testing DipDup projects
  src/dipdup/cli.py
  src/dipdup/database.py
  src/dipdup/hasura.py
  src/dipdup/test.py
  tests/__init__.py
  tests/configs/test_postgres.yaml
  tests/configs/test_postgres_immune.yaml
  tests/configs/test_sqlite.yaml
  tests/configs/test_sqlite_immune.yaml
  tests/test_demos.py
  tests/test_hasura.py
  tests/test_index/test_tzkt_operations.py
  tests/test_schema.py
Labels: improvement

#871 Add balances index
  CHANGELOG.md
  docs/1.getting-started/7.indexes.md
  docs/2.indexes/8.tezos_tzkt_token_balances.md
  src/demo_token_balances/.dockerignore
  src/demo_token_balances/.gitignore
  src/demo_token_balances/README.md
  src/demo_token_balances/__init__.py
  src/demo_token_balances/abi/.keep
  src/demo_token_balances/configs/.keep
  src/demo_token_balances/configs/dipdup.compose.yaml
  src/demo_token_balances/configs/dipdup.sqlite.yaml
  src/demo_token_balances/configs/dipdup.swarm.yaml
  src/demo_token_balances/configs/replay.yaml
  src/demo_token_balances/deploy/.env.default
  src/demo_token_balances/deploy/.keep
  src/demo_token_balances/deploy/Dockerfile
  src/demo_token_balances/deploy/compose.sqlite.yaml
  src/demo_token_balances/deploy/compose.swarm.yaml
  src/demo_token_balances/deploy/compose.yaml
  src/demo_token_balances/deploy/sqlite.env.default
  src/demo_token_balances/deploy/swarm.env.default
  src/demo_token_balances/dipdup.yaml
  src/demo_token_balances/graphql/.keep
  src/demo_token_balances/handlers/.keep
  src/demo_token_balances/handlers/on_balance_update.py
  src/demo_token_balances/hasura/.keep
  src/demo_token_balances/hooks/.keep
  src/demo_token_balances/hooks/on_index_rollback.py
  src/demo_token_balances/hooks/on_reindex.py
  src/demo_token_balances/hooks/on_restart.py
  src/demo_token_balances/hooks/on_synchronized.py
  src/demo_token_balances/models/.keep
  src/demo_token_balances/models/__init__.py
  src/demo_token_balances/py.typed
  src/demo_token_balances/pyproject.toml
  src/demo_token_balances/sql/.keep
  src/demo_token_balances/sql/on_index_rollback/.keep
  src/demo_token_balances/sql/on_reindex/.keep
  src/demo_token_balances/sql/on_restart/.keep
  src/demo_token_balances/sql/on_synchronized/.keep
  src/demo_token_balances/types/.keep
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_tzkt_token_balances.py
  src/dipdup/context.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_token_balances/__init__.py
  src/dipdup/indexes/tezos_tzkt_token_balances/index.py
  src/dipdup/indexes/tezos_tzkt_token_balances/matcher.py
  src/dipdup/models/__init__.py
  src/dipdup/models/tezos_tzkt.py
  src/dipdup/projects/demo_token_balances/dipdup.yaml.j2
  src/dipdup/projects/demo_token_balances/handlers/on_balance_update.py.j2
  src/dipdup/projects/demo_token_balances/models/__init__.py.j2
  src/dipdup/projects/demo_token_balances/replay.yaml
  tests/configs/demo_token_balances.yml
  tests/test_demos.py
Labels: feature

#870 Ability to limit the scope of `init` command
  CHANGELOG.md
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/project.py
Labels: improvement

#853 `--unsafe` and `--compose` flags for `config env` command
  CHANGELOG.md
  src/dipdup/cli.py
Labels: improvement

#876 Fix filtering transfers by token_id
  CHANGELOG.md
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/datasources/tzkt/models.py
  src/dipdup/install.py
Labels: bug

#880 Update release notes
  docs/9.release-notes/1.v7.1.md
Labels: documentation

#881 Fix package metadata for demos
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/projects/base/pyproject.toml.j2
Labels: bug
