Repository dipdup-io/dipdup, pull requests merged in 2023-06, with the labels that each got.

#714 Notes about codestyle
  CONTRIBUTING.md
Labels: documentation

#711 Finish migration to `next` as default branch
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  CONTRIBUTING.md
  README.md
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-evm-events/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token/docker-compose.swarm.yml
  docs/advanced/internal-tables.md
  docs/examples/demo-projects.md
  docs/troubleshooting.md
  poetry.lock
  requirements.dev.txt
  requirements.txt
  src/dipdup/project.py
  src/dipdup/projects/base/docker-compose.swarm.yml.j2
Labels: chore

#717 Drop `metadata_interface` flag
  CHANGELOG.md
  docs/advanced/feature-flags.md
  docs/config/advanced.md
  docs/config/reference.md
  docs/include/dipdup-full.yml
  docs/release-notes/7.0.0.md
  src/dipdup/config/__init__.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
Labels: feature

#719 Fix `installer.yml` workflow
  .github/workflows/installer.yml
Labels: bug, ci/cd

#718 Rename event hooks to system hooks
  docs/SUMMARY.md
  docs/advanced/index-factories.md
  docs/advanced/sql.md
  docs/advanced/system-hooks.md
  docs/getting-started/core-concepts.md
  docs/release-notes/7.0.0.md
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/config/__init__.py
  src/dipdup/dipdup.py
Labels: documentation

#716 Drop `crash_reporting` flag
  CHANGELOG.md
  demos/demo-auction/dipdup.dev.yml
  demos/demo-auction/dipdup.prod.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/dipdup.dev.yml
  demos/demo-big-maps/dipdup.prod.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/dipdup.dev.yml
  demos/demo-dao/dipdup.prod.yml
  demos/demo-dao/replay.json
  demos/demo-dex/dipdup.dev.yml
  demos/demo-dex/dipdup.prod.yml
  demos/demo-dex/replay.json
  demos/demo-domains/dipdup.dev.yml
  demos/demo-domains/dipdup.prod.yml
  demos/demo-domains/replay.json
  demos/demo-events/dipdup.dev.yml
  demos/demo-events/dipdup.prod.yml
  demos/demo-events/replay.json
  demos/demo-evm-events/dipdup.dev.yml
  demos/demo-evm-events/dipdup.prod.yml
  demos/demo-evm-events/replay.json
  demos/demo-factories/dipdup.dev.yml
  demos/demo-factories/dipdup.prod.yml
  demos/demo-factories/replay.json
  demos/demo-head/dipdup.dev.yml
  demos/demo-head/dipdup.prod.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/dipdup.dev.yml
  demos/demo-nft-marketplace/dipdup.prod.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/dipdup.dev.yml
  demos/demo-raw/dipdup.prod.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/dipdup.dev.yml
  demos/demo-token-transfers/dipdup.prod.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/dipdup.dev.yml
  demos/demo-token/dipdup.prod.yml
  demos/demo-token/replay.json
  docs/advanced/feature-flags.md
  docs/config/reference.md
  docs/cookiecutter.json
  docs/include/dipdup-full.yml
  docs/release-notes/7.0.0.md
  docs/troubleshooting.md
  src/dipdup/config/__init__.py
  src/dipdup/project.py
  src/dipdup/projects/base/dipdup.dev.yml.j2
  src/dipdup/projects/base/dipdup.prod.yml.j2
  src/dipdup/sentry.py
Labels: feature, breaking change

#725 Fix `init` crash when package name is equal to one of typenames
  CHANGELOG.md
  Makefile
  demos/demo-auction/docker-compose.swarm.yml
  demos/demo-auction/docker-compose.yml
  demos/demo-auction/replay.json
  demos/demo-big-maps/docker-compose.swarm.yml
  demos/demo-big-maps/docker-compose.yml
  demos/demo-big-maps/replay.json
  demos/demo-dao/docker-compose.swarm.yml
  demos/demo-dao/docker-compose.yml
  demos/demo-dao/replay.json
  demos/demo-dex/docker-compose.swarm.yml
  demos/demo-dex/docker-compose.yml
  demos/demo-dex/replay.json
  demos/demo-domains/docker-compose.swarm.yml
  demos/demo-domains/docker-compose.yml
  demos/demo-domains/replay.json
  demos/demo-events/docker-compose.swarm.yml
  demos/demo-events/docker-compose.yml
  demos/demo-events/replay.json
  demos/demo-factories/docker-compose.swarm.yml
  demos/demo-factories/docker-compose.yml
  demos/demo-factories/replay.json
  demos/demo-head/docker-compose.swarm.yml
  demos/demo-head/docker-compose.yml
  demos/demo-head/replay.json
  demos/demo-nft-marketplace/docker-compose.swarm.yml
  demos/demo-nft-marketplace/docker-compose.yml
  demos/demo-nft-marketplace/replay.json
  demos/demo-raw/docker-compose.swarm.yml
  demos/demo-raw/docker-compose.yml
  demos/demo-raw/replay.json
  demos/demo-token-transfers/docker-compose.swarm.yml
  demos/demo-token-transfers/docker-compose.yml
  demos/demo-token-transfers/replay.json
  demos/demo-token/docker-compose.swarm.yml
  demos/demo-token/docker-compose.yml
  demos/demo-token/replay.json
  docs/cookiecutter.json
  docs/theme/index.hbs
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/codegen.py
  src/dipdup/project.py
  src/dipdup/utils/__init__.py
Labels: bug

#726 Add script for live doc rerendering to md
  .github/workflows/docs.yml
  Makefile
  docs/Makefile
  docs/book.css
  docs/book.toml
  docs/cli-reference.rst
  docs/conf.py
  docs/config-reference.rst
  docs/context-reference.rst
  docs/dump_references.py
  docs/index.rst
  docs/make.bat
  docs/mdbook-admonish.css
  docs/mdbook-project
  docs/mdbook-summary
  poetry.lock
  pyproject.toml
  scripts/watch_docs.py
Labels: documentation, ci/cd
