Repository dipdup-io/dipdup, pull requests merged in 2024-01, with the labels that each got.

#915 Smart Rollup Execute Operation
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_tzkt_operations.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
  src/dipdup/models/tezos_tzkt.py
Labels: feature

#919 Fix a few bugs in tezos.tzkt.operations and internal helpers
  CHANGELOG.md
  docs/7.references/2.config.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
  schema.json
  src/demo_domains/types/name_registry/tezos_parameters/admin_update.py
  src/demo_domains/types/name_registry/tezos_parameters/execute.py
  src/demo_domains/types/name_registry/tezos_storage.py
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_tzkt_operations.py
  src/dipdup/datasources/abi_etherscan.py
  src/dipdup/http.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
  tests/test_models.py
Labels: bug

#920 7.3.0 release docs
  .github/workflows/docs.yml
  CHANGELOG.md
  Makefile
  README.md
  docs/1.getting-started/3.config.md
  docs/1.getting-started/4.package.md
  docs/1.getting-started/6.datasources.md
  docs/1.getting-started/7.indexes.md
  docs/12.faq.md
  docs/13.troubleshooting.md
  docs/15.thanks.md
  docs/2.indexes/5.tezos_tzkt_operations.md
  docs/4.graphql/4.genql.md
  docs/5.advanced/3.sql.md
  docs/5.advanced/4.metadata-interface.md
  docs/6.deployment/4.prometheus.md
  docs/6.deployment/5.logging.md
  docs/7.references/1.cli.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/7.references/4.api.md
  docs/8.examples/1.demos.md
  docs/8.examples/2.in-production.md
  docs/9.release-notes/1.v7.3.md
  docs/9.release-notes/2.v7.2.md
  docs/9.release-notes/3.v7.1.md
  docs/9.release-notes/4.v7.0.md
  docs/9.release-notes/5.v6.5.md
  docs/9.release-notes/6.history.md
  docs/9.release-notes/_footer.md
  docs/_static/.keep
  docs/config-reference.rst
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  schema.json
  scripts/demos.py
  scripts/docs.py
  scripts/dump_references.py
  scripts/dump_schema.py
  scripts/init_demos.py
  scripts/update_demos.py
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
Labels: documentation, ci/cd

#923 Fix and update Etherlink demo
  CHANGELOG.md
  Makefile
  docs/1.getting-started/6.datasources.md
  docs/1.getting-started/7.indexes.md
  docs/2.indexes/5.tezos_tzkt_operations.md
  docs/9.release-notes/1.v7.3.md
  docs/9.release-notes/2.v7.2.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
  scripts/demos.py
  scripts/docs.py
  src/demo_auction/Makefile
  src/demo_big_maps/Makefile
  src/demo_blank/Makefile
  src/demo_dao/Makefile
  src/demo_dex/Makefile
  src/demo_domains/Makefile
  src/demo_etherlink/Makefile
  src/demo_etherlink/deploy/.env.default
  src/demo_etherlink/deploy/sqlite.env.default
  src/demo_etherlink/deploy/swarm.env.default
  src/demo_etherlink/dipdup.yaml
  src/demo_etherlink/handlers/on_deposit.py
  src/demo_etherlink/handlers/on_rollup_call.py
  src/demo_etherlink/handlers/on_withdraw.py
  src/demo_etherlink/types/rollup/tezos_parameters/default.py
  src/demo_etherlink/types/ticket_helper/tezos_parameters/default.py
  src/demo_etherlink/types/ticket_helper/tezos_storage.py
  src/demo_etherlink/types/ticketer/tezos_parameters/deposit.py
  src/demo_etherlink/types/ticketer/tezos_parameters/withdraw.py
  src/demo_etherlink/types/ticketer/tezos_storage.py
  src/demo_events/Makefile
  src/demo_evm_events/Makefile
  src/demo_factories/Makefile
  src/demo_head/Makefile
  src/demo_nft_marketplace/Makefile
  src/demo_raw/Makefile
  src/demo_token/Makefile
  src/demo_token_balances/Makefile
  src/demo_token_transfers/Makefile
  src/demo_uniswap/Makefile
  src/dipdup/config/tezos_tzkt_operations.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/projects/base/Makefile.j2
  src/dipdup/projects/demo_etherlink/dipdup.yaml.j2
  src/dipdup/projects/demo_etherlink/handlers/on_rollup_call.py.j2
  tests/configs/demo_etherlink.yaml
Labels: documentation

#918 EVM networks support page
  Makefile
  docs/5.advanced/6.evm-compatible.md
  docs/7.references/1.cli.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  pdm.lock
  pyproject.toml
  scripts/docs.py
  src/demo_evm_events/deploy/.env.default
  src/demo_evm_events/deploy/sqlite.env.default
  src/demo_evm_events/deploy/swarm.env.default
  src/demo_evm_events/dipdup.yaml
  src/dipdup/projects/demo_evm_events/dipdup.yaml.j2
Labels: documentation

#928 Update EVM demos, make `ws_url` optional
  .github/workflows/release.yml
  .github/workflows/test.yml
  Makefile
  docs/0.quickstart-evm.md
  docs/0.quickstart-tezos.md
  docs/1.getting-started/6.datasources.md
  docs/15.thanks.md
  docs/2.indexes/1.evm_subsquid_events.md
  docs/3.datasources/3.evm_node.md
  docs/3.datasources/4.evm_subsquid.md
  docs/4.graphql/4.genql.md
  docs/5.advanced/6.evm-compatible.md
  docs/6.deployment/1.database.md
  docs/6.deployment/4.prometheus.md
  docs/7.references/2.config.md
  docs/8.examples/2.in-production.md
  docs/9.release-notes/2.v7.2.md
  docs/9.release-notes/4.v7.0.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  schema.json
  scripts/docs.py
  src/demo_evm_events/deploy/.env.default
  src/demo_evm_events/deploy/sqlite.env.default
  src/demo_evm_events/deploy/swarm.env.default
  src/demo_evm_events/dipdup.yaml
  src/demo_uniswap/deploy/.env.default
  src/demo_uniswap/deploy/sqlite.env.default
  src/demo_uniswap/deploy/swarm.env.default
  src/demo_uniswap/dipdup.yaml
  src/demo_uniswap/handlers/factory/pool_created.py
  src/demo_uniswap/models/position.py
  src/dipdup/config/evm_node.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/exceptions.py
  src/dipdup/hasura.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/projects/demo_evm_events/dipdup.yaml.j2
  src/dipdup/projects/demo_uniswap/dipdup.yaml.j2
  src/dipdup/projects/demo_uniswap/handlers/factory/pool_created.py.j2
  src/dipdup/projects/demo_uniswap/models/position.py.j2
  src/dipdup/prometheus.py
  tests/configs/demo_evm_events.yml
  tests/configs/demo_evm_events_node.yml
  tests/test_config/test_custom_config.py
Labels: documentation, ci/cd

#929 Bump version 7.3.1
  CHANGELOG.md
  Makefile
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/codegen/tezos_tzkt.py
Labels: ci/cd

#930 Fix MD055/table-pipe-style warning
  docs/9.release-notes/6.history.md
Labels: ci/cd

#931 Rename EVM networks page
  .github/workflows/docs.yml
  docs/5.advanced/6.evm-networks.md
Labels: documentation, ci/cd
