Repository dipdup-io/dipdup, pull requests merged in 2024-07, with the labels that each got.

#1048 Remove starknet type import for memory optimization
  src/dipdup/package.py
Labels: improvement

#1049 More lazy imports, LOW_MEMORY flag
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_evm_events/models/__init__.py
  src/demo_evm_transactions/models/__init__.py
  src/demo_starknet_events/models/__init__.py
  src/dipdup/codegen/evm.py
  src/dipdup/config/evm.py
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/env.py
  src/dipdup/fetcher.py
  src/dipdup/http.py
  src/dipdup/indexes/evm.py
  src/dipdup/indexes/evm_events/matcher.py
  src/dipdup/indexes/evm_node.py
  src/dipdup/indexes/evm_transactions/matcher.py
  src/dipdup/models/__init__.py
  src/dipdup/projects/demo_evm_events/models/__init__.py.j2
  src/dipdup/projects/demo_evm_transactions/models/__init__.py.j2
  src/dipdup/projects/demo_starknet_events/models/__init__.py.j2
Labels: improvement

#1050 Fixed typo in `iter_events` method name
  CHANGELOG.md
  docs/5.advanced/2.feature-flags.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/indexes/evm_events/fetcher.py
Labels: documentation, chore

#1052 Fix `--pre` installer flag
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  scripts/demos.py
  src/dipdup/install.py
Labels: bug

#1051 Drop `pyarrow`, fix `make image` command
  .github/workflows/installer.yml
  CHANGELOG.md
  Makefile
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/demos.py
  src/demo_auction/Makefile
  src/demo_big_maps/Makefile
  src/demo_blank/Makefile
  src/demo_dao/Makefile
  src/demo_dex/Makefile
  src/demo_domains/Makefile
  src/demo_etherlink/Makefile
  src/demo_events/Makefile
  src/demo_evm_events/Makefile
  src/demo_evm_transactions/Makefile
  src/demo_factories/Makefile
  src/demo_head/Makefile
  src/demo_nft_marketplace/Makefile
  src/demo_raw/Makefile
  src/demo_token/Makefile
  src/demo_token_balances/Makefile
  src/demo_token_transfers/Makefile
  src/demo_uniswap/Makefile
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/projects/base/Makefile.j2
  tests/test_demos.py
Labels: chore

#1054 Bump version 7.5.8
  CHANGELOG.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pyproject.toml
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/install.py
Labels: chore

#1055 Fix `CachedModel` preloading
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/dipdup.py
  src/dipdup/models/__init__.py
Labels: bug, v7, v8

#1056 Force update `aiosqlite` to 0.20.0
  Makefile
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
Labels: chore, v7, v8

#1061 Improve config jsonschema generation
  schema.json
  scripts/docs.py
  src/dipdup/config/__init__.py
Labels: improvement

#1064 Lint, fix autodoc refs
  docs/7.references/2.config.md
  docs/7.references/4.models.md
  docs/9.release-notes/_8.0_changelog.md
  docs/config.rst
  docs/models.rst
  scripts/docs.py
  src/dipdup/config/tezos_operations.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/hasura.py
  src/dipdup/indexes/tezos_operations/matcher.py
  src/dipdup/models/tezos.py
  src/dipdup/models/tezos_tzkt.py
Labels: chore

#1063 Backport: Fix CachedModel preloading (#1055)
  CHANGELOG.md
  src/dipdup/dipdup.py
  src/dipdup/models/__init__.py
Labels: bug

#1062 Backport: Improve config jsonschema generation (#1061)
  docs/7.references/2.config.md
  schema.json
  scripts/docs.py
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/config/__init__.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/config/evm_subsquid_traces.py
  src/dipdup/config/evm_subsquid_transactions.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/evm_subsquid_traces/fetcher.py
  src/dipdup/indexes/evm_subsquid_traces/index.py
  src/dipdup/indexes/evm_subsquid_traces/matcher.py
Labels: improvement, v7

#1065 Publish JSON schemas for config validation and autocompletion
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  schemas/dipdup-2.0.json
  schemas/dipdup-3.0.json
  scripts/docs.py
  src/dipdup/config/__init__.py
Labels: improvement

#1066 Find and mark/fix broken external links
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/36.polygon.md
  docs/10.supported-networks/43.taiko.md
  docs/10.supported-networks/44.tanssi.md
  docs/10.supported-networks/7.bitgert.md
  docs/8.examples/2.in-production.md
  docs/9.release-notes/7.v7.0.md
  docs/9.release-notes/_8.0_changelog.md
  schemas/dipdup-3.0.json
  scripts/docs.py
Labels: documentation

#1071 Improve fetching event batches from node
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/datasources/abi_etherscan.py
  src/dipdup/indexes/evm_events/fetcher.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/evm_node.py
Labels: bug

#1072 Backport: Improve fetching event batches from node (#1071)
  CHANGELOG.md
  src/dipdup/datasources/abi_etherscan.py
  src/dipdup/indexes/evm_node.py
  src/dipdup/indexes/evm_subsquid_events/fetcher.py
  src/dipdup/indexes/evm_subsquid_events/index.py
Labels: bug

#1070 Bump version 7.5.9
  .vscode/launch.json
  CHANGELOG.md
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/36.polygon.md
  docs/10.supported-networks/43.taiko.md
  docs/10.supported-networks/44.tanssi.md
  docs/10.supported-networks/7.bitgert.md
  docs/10.supported-networks/_dir.yml
  docs/14.contributing.md
  docs/7.references/3.context.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/docs.py
  src/dipdup/cli.py
  src/dipdup/models/__init__.py
Labels: chore

#1076 Fix integration test configs
  docs/14.contributing.md
  tests/configs/demo_evm_events.yml
  tests/configs/demo_evm_events_node.yml
  tests/configs/demo_evm_transactions.yml
  tests/configs/demo_evm_transactions_node.yml
  tests/configs/test_evm.yml
  tests/test_demos.py
Labels: ci/cd

#1074 Use `uvloop` to improve asyncio performance
  CHANGELOG.md
  docs/5.advanced/5.performance.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/sentry.py
  src/dipdup/sys.py
Labels: improvement

#1075 Fixed Tezos Smart Rollup Cemented Commitment Subscription
  CHANGELOG.md
  src/dipdup/config/tezos_operations.py
Labels: bug

#1077 Fix nested click invocations
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/cli.py
  src/dipdup/config/tezos_operations.py
Labels: bug

#1078 Use `uvloop` to improve asyncio performance (#1074)
  CHANGELOG.md
  docs/14.contributing.md
  docs/5.advanced/5.performance.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/sentry.py
  src/dipdup/sys.py
  tests/configs/demo_evm_events.yml
  tests/configs/demo_evm_events_node.yml
  tests/configs/demo_evm_transactions.yml
  tests/configs/demo_evm_transactions_node.yml
  tests/configs/test_evm.yml
  tests/test_demos.py
Labels: improvement

#1079 Update F.A.Q page
  docs/1.getting-started/4.package.md
  docs/12.faq.md
Labels: documentation
