Repository dipdup-io/dipdup, pull requests merged in 2024-10, with the labels that each got.

#1113 Cache latest release from GitHub for version check in xdg_shared_dir #1095
  pdm.lock
  pyproject.toml
  requirements.txt
  src/dipdup/cli.py
Labels: community, improvement

#1116 Lint, update contributors
  docs/16.thanks.md
  docs/7.references/2.config.md
  docs/9.release-notes/_8.0_changelog.md
  schemas/dipdup-3.0.json
  src/dipdup/cli.py
  src/dipdup/config/__init__.py
  src/dipdup/hasura.py
Labels: chore

#1110 Use `aerich` for database migrations
  CHANGELOG.md
  docs/1.getting-started/5.database.md
  docs/7.references/1.cli.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  src/dipdup/aerich.py
  src/dipdup/cli.py
  src/dipdup/context.py
  src/dipdup/database.py
  src/dipdup/dipdup.py
  src/dipdup/exceptions.py
  src/dipdup/package.py
Labels: feature, community

#1121 Lint, fix mypy warnings
  src/dipdup/aerich.py
  src/dipdup/cli.py
  src/dipdup/dipdup.py
Labels: chore

#1122 Reload constants in dipdup.env after applying env-files
  pdm.lock
  scripts/docs.py
  src/dipdup/cli.py
  src/dipdup/env.py
Labels: bug

#1115 Add __repr__ methods
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/models/__init__.py
  src/dipdup/package.py
  src/dipdup/transactions.py
Labels: community, improvement

#1125 Update database docs, fix tests
  docs/1.getting-started/5.database.md
  pdm.lock
  requirements.txt
  scripts/docs.py
  src/dipdup/cli.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/models/__init__.py
  src/dipdup/package.py
  src/dipdup/transactions.py
  tests/test_schema.py
Labels: documentation

#1126 Don't add aerich.models to tortoise_config if migrations is disabled
  src/dipdup/aerich.py
  src/dipdup/cli.py
  src/dipdup/database.py
  src/dipdup/dipdup.py
Labels: bug, community

#1102 Etherscan failover ABI fetcher
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/datasources/__init__.py
  src/dipdup/datasources/abi_etherscan.py
Labels: improvement

#1118 feat: add interactive config generator
  .gitignore
  requirements.txt
  src/dipdup/interactive.py
  src/dipdup/project.py
  src/dipdup/projects/demo_blank/dipdup.yaml.j2
Labels: feature, community

#1131 Refactor `performance._MetricManager` and `prometheus.Metrics`
  docs/5.advanced/3.monitoring.md
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/evm.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/evm_transactions/index.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/indexes/tezos_big_maps/index.py
  src/dipdup/indexes/tezos_operations/index.py
  src/dipdup/performance.py
  src/dipdup/prometheus.py
  tests/test_dipdup.py
Labels: community, improvement

#1136 Post-ODHack refactoring
  .gitignore
  CHANGELOG.md
  Makefile
  docs/1.getting-started/5.database.md
  docs/16.thanks.md
  docs/5.advanced/3.monitoring.md
  docs/5.advanced/_metrics_table.md
  docs/7.references/1.cli.md
  docs/7.references/2.config.md
  docs/9.release-notes/1.v8.1.md
  docs/9.release-notes/2.v8.0.md
  docs/9.release-notes/3.v7.5.md
  docs/9.release-notes/4.v7.4.md
  docs/9.release-notes/5.v7.3.md
  docs/9.release-notes/6.v7.2.md
  docs/9.release-notes/7.v7.1.md
  docs/9.release-notes/8.v7.0.md
  docs/9.release-notes/_8.0_changelog.md
  docs/9.release-notes/_8.1_changelog.md
  pdm.lock
  requirements.txt
  schemas/dipdup-2.0.json
  schemas/dipdup-3.0.json
  scripts/docs.py
  src/dipdup/__init__.py
  src/dipdup/_survey.py
  src/dipdup/_version.py
  src/dipdup/cli.py
  src/dipdup/config/__init__.py
  src/dipdup/config/evm.py
  src/dipdup/config/starknet.py
  src/dipdup/config/tezos.py
  src/dipdup/context.py
  src/dipdup/database.py
  src/dipdup/dipdup.py
  src/dipdup/fetcher.py
  src/dipdup/hasura.py
  src/dipdup/index.py
  src/dipdup/models/__init__.py
  src/dipdup/package.py
  src/dipdup/performance.py
  src/dipdup/project.py
  src/dipdup/projects/demo_blank/dipdup.yaml.j2
  src/dipdup/sys.py
  src/dipdup/templates/replay.yaml.j2
  src/dipdup/utils.py
Labels: chore
