Repository dipdup-io/dipdup, pull requests merged in 2024-08, with the labels that each got.

#1081 Some benchmarks
  benchmarks/Makefile
  benchmarks/README.md
  benchmarks/local_postgres.yaml
  benchmarks/oneshot_demo_evm_events.yaml
  benchmarks/oneshot_demo_starknet_events.yaml
  benchmarks/oneshot_demo_tezos_domains.yaml
Labels: documentation, ci/cd

#1082 Bump version 7.5.10
  CHANGELOG.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/cli.py
  src/dipdup/dipdup.py
Labels: chore

#1060 `batch` index handler
  CHANGELOG.md
  Makefile
  benchmarks/Makefile
  benchmarks/README.md
  docs/7.references/3.context.md
  docs/9.release-notes/_8.0_changelog.md
  pyproject.toml
  src/demo_blank/handlers/batch.py
  src/demo_evm_events/handlers/batch.py
  src/demo_evm_transactions/handlers/batch.py
  src/demo_evm_uniswap/handlers/batch.py
  src/demo_starknet_events/handlers/batch.py
  src/demo_tezos_auction/handlers/batch.py
  src/demo_tezos_big_maps/handlers/batch.py
  src/demo_tezos_dao/handlers/batch.py
  src/demo_tezos_dex/handlers/batch.py
  src/demo_tezos_domains/handlers/batch.py
  src/demo_tezos_domains/handlers/on_update_expiry_map.py
  src/demo_tezos_domains/handlers/on_update_records.py
  src/demo_tezos_events/handlers/batch.py
  src/demo_tezos_factories/handlers/batch.py
  src/demo_tezos_head/handlers/batch.py
  src/demo_tezos_nft_marketplace/handlers/batch.py
  src/demo_tezos_raw/handlers/batch.py
  src/demo_tezos_token/handlers/batch.py
  src/demo_tezos_token_balances/handlers/batch.py
  src/demo_tezos_token_transfers/handlers/batch.py
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/codegen/tezos.py
  src/dipdup/config/__init__.py
  src/dipdup/config/_mixin.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/index.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/evm_transactions/index.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/indexes/tezos_big_maps/index.py
  src/dipdup/indexes/tezos_events/index.py
  src/dipdup/indexes/tezos_head/index.py
  src/dipdup/indexes/tezos_operations/index.py
  src/dipdup/indexes/tezos_token_balances/index.py
  src/dipdup/indexes/tezos_token_transfers/index.py
  src/dipdup/models/__init__.py
  src/dipdup/projects/demo_tezos_domains/handlers/on_update_expiry_map.py.j2
  src/dipdup/projects/demo_tezos_domains/handlers/on_update_records.py.j2
  src/dipdup/scheduler.py
  tests/test_utils.py
Labels: feature, v8

#1083 Fix typo in Starknet demo
  src/demo_starknet_events/handlers/on_transfer.py
  src/dipdup/projects/demo_starknet_events/handlers/on_transfer.py.j2
Labels: documentation

#1080 Refactor ABI processing, fix filtering events by signature
  CHANGELOG.md
  docs/7.references/2.config.md
  docs/9.release-notes/_8.0_changelog.md
  schemas/dipdup-3.0.json
  src/dipdup/abi/__init__.py
  src/dipdup/abi/cairo.py
  src/dipdup/abi/evm.py
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/config/evm.py
  src/dipdup/config/evm_transactions.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/evm.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/evm_events/matcher.py
  src/dipdup/indexes/evm_transactions/index.py
  src/dipdup/indexes/evm_transactions/matcher.py
  src/dipdup/indexes/starknet.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/indexes/starknet_events/matcher.py
  src/dipdup/package.py
Labels: bug, chore

#1085 Fix concurrency issue when using `get_or_create` method
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/config/__init__.py
Labels: bug

#1084 Refactor `tezos.operations` index tech debt
  src/dipdup/index.py
  src/dipdup/indexes/tezos_operations/index.py
  src/dipdup/indexes/tezos_operations/matcher.py
Labels: chore

#1088 Fixed typo in quickstart-tezos
  docs/0.quickstart-tezos.md
Labels: documentation
