Repository dipdup-io/dipdup, pull requests merged in 2024-02, with the labels that each got.

#940 Metadata networks unit test fixed
  CHANGELOG.md
  src/dipdup/models/tzip_metadata.py
Labels: bug, ci/cd

#939 Dots in typename should indicate nested packages
  CHANGELOG.md
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/config/__init__.py
Labels: bug

#938 EvmNodeDatasource._synchronize() optimisations
  CHANGELOG.md
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/config/__init__.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/indexes/evm_subsquid_events/index.py
Labels: improvement

#936 Do not consider config as oneshot if `tezos.tzkt.head` index is present
  CHANGELOG.md
  src/dipdup/dipdup.py
Labels: bug

#937 Added `DIPDUP_NO_VERSION_CHECK` and `DIPDUP_NO_SYMLINK` variables
  CHANGELOG.md
  docs/5.advanced/2.feature-flags.md
  src/dipdup/cli.py
  src/dipdup/env.py
  src/dipdup/package.py
Labels: improvement

#932 Make `withdrawals_root` field optional, fix empty HTTP urls before request
  CHANGELOG.md
  src/dipdup/http.py
  src/dipdup/models/evm_node.py
Labels: bug

#943 7.4 release docs update
  CHANGELOG.md
  CONTRIBUTING.md
  docs/12.faq.md
  docs/14.contributing.md
  docs/2.indexes/1.evm_subsquid_events.md
  docs/2.indexes/2.evm_subsquid_transactions.md
  docs/2.indexes/4.tezos_tzkt_events.md
  docs/2.indexes/_evm_subsquid.md
  docs/3.datasources/1.abi_etherscan.md
  docs/3.datasources/3.evm_node.md
  docs/3.datasources/4.evm_subsquid.md
  docs/3.datasources/_evm_banner.md
  docs/5.advanced/2.feature-flags.md
  docs/7.references/1.cli.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/9.release-notes/1.v7.4.md
  docs/9.release-notes/2.v7.3.md
  docs/9.release-notes/3.v7.2.md
  docs/9.release-notes/4.v7.1.md
  docs/9.release-notes/5.v7.0.md
  docs/9.release-notes/6.v6.5.md
  docs/9.release-notes/7.history.md
  docs/9.release-notes/_footer.md
  docs/cli.rst
  docs/config.rst
  docs/context.rst
  docs/index.rst
  pdm.lock
  requirements.dev.txt
  requirements.txt
  schema.json
  scripts/docs.py
  src/dipdup/cli.py
  src/dipdup/config/__init__.py
  src/dipdup/config/abi_etherscan.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_subsquid_transactions.py
  src/dipdup/config/tezos_tzkt.py
  src/dipdup/config/tezos_tzkt_big_maps.py
  src/dipdup/config/tezos_tzkt_events.py
  src/dipdup/config/tezos_tzkt_head.py
  src/dipdup/config/tezos_tzkt_operations.py
  src/dipdup/config/tezos_tzkt_token_balances.py
  src/dipdup/config/tezos_tzkt_token_transfers.py
  src/dipdup/context.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/exceptions.py
  src/dipdup/indexes/tezos_tzkt_operations/parser.py
  src/dipdup/models/__init__.py
  src/dipdup/models/tezos_tzkt.py
  src/dipdup/models/tzip_metadata.py
  src/dipdup/project.py
Labels: documentation

#945 Bump version 7.4.0
  docs/7.references/1.cli.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/cli.rst
  docs/config.rst
  docs/context.rst
  docs/index.rst
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/docs.py
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
Labels: ci/cd
