Repository dipdup-io/dipdup, pull requests merged in 2024-12, with the labels that each got.

#1145 Add Sonic
  docs/10.supported-networks/43.sonic.md
  docs/10.supported-networks/44.taiko.md
  docs/10.supported-networks/45.tanssi.md
  docs/10.supported-networks/46.x1.md
  docs/10.supported-networks/47.x-layer.md
  docs/10.supported-networks/48.zksync.md
  docs/10.supported-networks/49.zora.md
Labels: documentation

#1164 updated zora
  docs/10.supported-networks/50.zora.md
Labels: documentation

#1162 updated shiden
  docs/10.supported-networks/42.shiden.md
Labels: documentation

#1161 updated xlayer
  docs/10.supported-networks/48.x-layer.md
Labels: documentation

#1160 updated prom
  docs/10.supported-networks/38.prom.md
Labels: documentation

#1159 updated opbnb
  docs/10.supported-networks/34.opbnb.md
Labels: documentation

#1152 updated immutable
  docs/10.supported-networks/22.immutable-zkevm.md
Labels: documentation

#1153 updated merlin
  docs/10.supported-networks/28.merlin.md
Labels: documentation

#1154 updated mantle
  docs/10.supported-networks/27.mantle.md
Labels: documentation

#1156 updated metis
  docs/10.supported-networks/29.metis.md
Labels: documentation

#1155 fixed bob and dogechain
  docs/10.supported-networks/15.dogechain.md
  docs/10.supported-networks/9.bob.md
Labels: documentation

#1158 updated mode
  docs/10.supported-networks/31.mode.md
Labels: documentation

#1157 updated neon
  docs/10.supported-networks/33.neon.md
Labels: documentation

#1165 updated dfkchain
  docs/10.supported-networks/14.dfk-chain.md
Labels: documentation

#1166 Fix parsing config files after updating to pydantic 2.10.3
  CHANGELOG.md
  docs/7.references/2.config.md
  docs/9.release-notes/_8.0_changelog.md
  docs/conf.py
  pdm.lock
  pyproject.toml
  requirements.txt
  schemas/dipdup-3.0.json
  scripts/docs.py
  src/dipdup/config/__init__.py
  src/dipdup/config/_mixin.py
  src/dipdup/config/abi_etherscan.py
  src/dipdup/config/coinbase.py
  src/dipdup/config/evm.py
  src/dipdup/config/evm_events.py
  src/dipdup/config/evm_node.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_transactions.py
  src/dipdup/config/http.py
  src/dipdup/config/ipfs.py
  src/dipdup/config/starknet.py
  src/dipdup/config/starknet_events.py
  src/dipdup/config/starknet_node.py
  src/dipdup/config/starknet_subsquid.py
  src/dipdup/config/tezos.py
  src/dipdup/config/tezos_big_maps.py
  src/dipdup/config/tezos_events.py
  src/dipdup/config/tezos_head.py
  src/dipdup/config/tezos_operations.py
  src/dipdup/config/tezos_token_balances.py
  src/dipdup/config/tezos_token_transfers.py
  src/dipdup/config/tezos_tzkt.py
  src/dipdup/config/tzip_metadata.py
  src/dipdup/project.py
Labels: bug

#1173 Update docs publishing CI
  .github/workflows/docs.yml
Labels: ci/cd

#1171 Support complex types in Starknet ABI
  src/dipdup/abi/cairo.py
  src/dipdup/config/starknet.py
  src/dipdup/config/starknet_events.py
  src/dipdup/datasources/starknet_node.py
  src/dipdup/indexes/starknet_events/matcher.py
  tests/configs/demo_starknet_events.yml
  tests/test_config/test_config.py
Labels: bug, community

#1176 Subsquid deserialization fixes
  CHANGELOG.md
  src/dipdup/models/evm.py
Labels: bug, critical
