Repository dipdup-io/dipdup, pull requests merged in 2024-05, with the labels that each got.

#1009 Update GH actions, bump deps
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
Labels: ci/cd

#1006 Starknet subsquid datasource
  src/dipdup/config/starknet_subsquid.py
  src/dipdup/datasources/abstract_subsquid.py
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/datasources/starknet_subsquid.py
  src/dipdup/models/evm_subsquid.py
  src/dipdup/models/starknet.py
  src/dipdup/models/starknet_subsquid.py
  src/dipdup/models/subsquid.py
Labels: feature

#1010 Update performance metrics and status message
  CHANGELOG.md
  docs/7.references/4.models.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  requirements.dev.txt
  schema.json
  src/dipdup/datasources/evm_node.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/tezos_big_maps/index.py
  src/dipdup/indexes/tezos_operations/index.py
  src/dipdup/models/tzip_metadata.py
  src/dipdup/performance.py
Labels: bug, improvement

#1013 Update performance metrics and status message (v7)
  CHANGELOG.md
  docs/7.references/2.config.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  schema.json
  src/dipdup/datasources/evm_node.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/models/tzip_metadata.py
  src/dipdup/performance.py
Labels: bug, improvement

#1014 Bump version 7.5.6
  CHANGELOG.md
  docs/8.examples/_demos_table.md
  pyproject.toml
  requirements.dev.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
Labels: ci/cd

#1015 Publish installer in docs workflow
  .github/workflows/docs.yml
  .github/workflows/installer.yml
Labels: ci/cd

#1023 Fix matching logs when filtering by topic0 (next)
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/codegen/evm.py
  src/dipdup/config/__init__.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/evm_events/matcher.py
  src/dipdup/package.py
Labels: bug, v8

#1024 Fix matching logs when filtering by topic0
  CHANGELOG.md
  docs/9.release-notes/_7.5_changelog.md
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/config/__init__.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_events/matcher.py
  src/dipdup/package.py
  tests/profile_abi_decoding.py
Labels: bug, v7

#1025 Bump version 7.5.7
  docs/8.examples/_demos_table.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/performance.py
Labels: chore

#1026 Update changelog for 7.5.7
  CHANGELOG.md
  docs/9.release-notes/_7.5_changelog.md
Labels: documentation

#1027 Sync changelog with `current`
  CHANGELOG.md
  docs/9.release-notes/_7.5_changelog.md
  docs/9.release-notes/_8.0_changelog.md
Labels: documentation

#1028 Minor Starknet index fixes
  docs/7.references/2.config.md
  docs/7.references/4.models.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_8.0_changelog.md
  docs/config.rst
  docs/models.rst
  pdm.lock
  requirements.dev.txt
  requirements.txt
  schema.json
  scripts/demos.py
  scripts/docs.py
  src/dipdup/codegen/starknet.py
  src/dipdup/config/__init__.py
  src/dipdup/config/evm.py
  src/dipdup/config/evm_node.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/starknet.py
  src/dipdup/config/starknet_events.py
  src/dipdup/config/starknet_subsquid.py
  src/dipdup/config/tezos.py
  src/dipdup/config/tezos_tzkt.py
  src/dipdup/indexes/evm_events/index.py
  src/dipdup/indexes/starknet_events/matcher.py
  src/dipdup/package.py
  src/dipdup/performance.py
Labels: chore

#1021 Update tortoise-orm to 0.21.2
  CHANGELOG.md
  docs/12.faq.md
  docs/5.advanced/5.performance.md
  docs/9.release-notes/7.v7.0.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_blank/models/__init__.py
  src/demo_evm_events/models/__init__.py
  src/demo_evm_transactions/models/__init__.py
  src/demo_evm_uniswap/models/__init__.py
  src/demo_starknet_events/models/__init__.py
  src/demo_tezos_auction/models/__init__.py
  src/demo_tezos_big_maps/models/__init__.py
  src/demo_tezos_dao/models/__init__.py
  src/demo_tezos_dex/models/__init__.py
  src/demo_tezos_domains/models/__init__.py
  src/demo_tezos_etherlink/models/__init__.py
  src/demo_tezos_events/models/__init__.py
  src/demo_tezos_factories/models/__init__.py
  src/demo_tezos_head/models/__init__.py
  src/demo_tezos_nft_marketplace/models/__init__.py
  src/demo_tezos_token/models/__init__.py
  src/demo_tezos_token_balances/models/__init__.py
  src/demo_tezos_token_transfers/models/__init__.py
  src/dipdup/config/__init__.py
  src/dipdup/fields.py
  src/dipdup/models/__init__.py
  src/dipdup/projects/demo_evm_events/models/__init__.py.j2
  src/dipdup/projects/demo_evm_transactions/models/__init__.py.j2
  src/dipdup/projects/demo_evm_uniswap/models/__init__.py.j2
  src/dipdup/projects/demo_starknet_events/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_auction/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_big_maps/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_dao/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_dex/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_domains/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_factories/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_nft_marketplace/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_token/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_token_balances/models/__init__.py.j2
  src/dipdup/projects/demo_tezos_token_transfers/models/__init__.py.j2
  src/dipdup/templates/models.py
Labels: bug, improvement

#1019 Generate `launch.json` configurations for demo projects
  .vscode/launch.json
  scripts/docs.py
Labels: chore
