Repository dipdup-io/dipdup, pull requests merged in 2024-06, with the labels that each got.

#1029 Sync supported networks with Subsquid
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/23.kakarot.md
  docs/10.supported-networks/24.karak.md
  docs/10.supported-networks/25.linea.md
  docs/10.supported-networks/26.mantle.md
  docs/10.supported-networks/27.merlin.md
  docs/10.supported-networks/28.metis.md
  docs/10.supported-networks/29.mineplex.md
  docs/10.supported-networks/30.mode.md
  docs/10.supported-networks/31.moonbeam.md
  docs/10.supported-networks/32.neon.md
  docs/10.supported-networks/33.opbnb.md
  docs/10.supported-networks/34.optimism.md
  docs/10.supported-networks/35.peaq.md
  docs/10.supported-networks/36.polygon.md
  docs/10.supported-networks/37.prom.md
  docs/10.supported-networks/38.scroll.md
  docs/10.supported-networks/39.shibarium.md
  docs/10.supported-networks/40.shibuya.md
  docs/10.supported-networks/41.shiden.md
  docs/10.supported-networks/42.scale.md
  docs/10.supported-networks/43.taiko.md
  docs/10.supported-networks/44.tanssi.md
  docs/10.supported-networks/45.x1.md
  docs/10.supported-networks/46.x-layer.md
  docs/10.supported-networks/47.zksync.md
  docs/10.supported-networks/48.zora.md
Labels: documentation

#1030 Update supported networks on 7.5 branch
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/1.arbitrum.md
  docs/10.supported-networks/10.core.md
  docs/10.supported-networks/11.cyber.md
  docs/10.supported-networks/12.cyberconnect.md
  docs/10.supported-networks/13.dfk-chain.md
  docs/10.supported-networks/14.dogechain.md
  docs/10.supported-networks/15.ethereum.md
  docs/10.supported-networks/16.etherlink.md
  docs/10.supported-networks/17.exosama.md
  docs/10.supported-networks/18.fantom.md
  docs/10.supported-networks/19.flare.md
  docs/10.supported-networks/2.astar.md
  docs/10.supported-networks/20.gnosis.md
  docs/10.supported-networks/21.immutable-zkevm.md
  docs/10.supported-networks/22.hokum.md
  docs/10.supported-networks/23.kakarot.md
  docs/10.supported-networks/24.karak.md
  docs/10.supported-networks/25.linea.md
  docs/10.supported-networks/26.mantle.md
  docs/10.supported-networks/27.merlin.md
  docs/10.supported-networks/28.metis.md
  docs/10.supported-networks/29.mineplex.md
  docs/10.supported-networks/3.avalanche.md
  docs/10.supported-networks/30.mode.md
  docs/10.supported-networks/31.moonbeam.md
  docs/10.supported-networks/32.neon.md
  docs/10.supported-networks/33.opbnb.md
  docs/10.supported-networks/34.optimism.md
  docs/10.supported-networks/35.peaq.md
  docs/10.supported-networks/36.polygon.md
  docs/10.supported-networks/37.prom.md
  docs/10.supported-networks/38.scroll.md
  docs/10.supported-networks/39.shibarium.md
  docs/10.supported-networks/4.base.md
  docs/10.supported-networks/40.shibuya.md
  docs/10.supported-networks/41.shiden.md
  docs/10.supported-networks/42.scale.md
  docs/10.supported-networks/43.taiko.md
  docs/10.supported-networks/44.tanssi.md
  docs/10.supported-networks/45.x1.md
  docs/10.supported-networks/46.x-layer.md
  docs/10.supported-networks/47.zksync.md
  docs/10.supported-networks/48.zora.md
  docs/10.supported-networks/5.berachain.md
  docs/10.supported-networks/6.binance-smart-chain.md
  docs/10.supported-networks/7.bitgert.md
  docs/10.supported-networks/8.blast.md
  docs/10.supported-networks/9.canto.md
  docs/10.supported-networks/_dir.yml
  docs/10.supported-networks/_intro.md
  docs/2.indexes/_evm.md
  docs/3.datasources/_evm_banner.md
  docs/5.advanced/6.evm-networks.md
  docs/9.release-notes/1.v7.5.md
Labels: documentation

#1020 Full project migration support for 3.0 spec
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/exceptions.py
  src/dipdup/migrations/__init__.py
  src/dipdup/migrations/three_zero.py
  src/dipdup/package.py
Labels: improvement

#1032 Indexes refactoring
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/package.py
Labels: chore

#1033 Starknet docs, 8.0 release notes
  CHANGELOG.md
  docs/0.quickstart-starknet.md
  docs/1.getting-started/6.datasources.md
  docs/1.getting-started/7.indexes.md
  docs/2.indexes/10.tezos_token_transfers.md
  docs/2.indexes/3.starknet_events.md
  docs/2.indexes/4.tezos_big_maps.md
  docs/2.indexes/5.tezos_events.md
  docs/2.indexes/6.tezos_head.md
  docs/2.indexes/7.tezos_operations.md
  docs/2.indexes/8.tezos_operations_unfiltered.md
  docs/2.indexes/9.tezos_token_balances.md
  docs/2.indexes/_starknet.md
  docs/3.datasources/7.starknet_subsquid.md
  docs/3.datasources/8.tezos_tzkt.md
  docs/3.datasources/9.tzip_metadata.md
  docs/9.release-notes/1.v8.0.md
  docs/9.release-notes/4.v7.3.md
  docs/9.release-notes/5.v7.2.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/dipdup/models/__init__.py
  src/dipdup/project.py
Labels: documentation

#1035 Minor indexes refactoring
  src/dipdup/index.py
  src/dipdup/indexes/evm.py
  src/dipdup/indexes/starknet.py
  src/dipdup/indexes/starknet_events/fetcher.py
  src/dipdup/indexes/starknet_events/index.py
Labels: chore

#1036 8.0 interface update
  CHANGELOG.md
  docs/0.quickstart-evm.md
  docs/0.quickstart-starknet.md
  docs/0.quickstart-tezos.md
  docs/1.getting-started/1.installation.md
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/_dir.yml
Labels: ci/cd

#1037 Update Quickstart page
  docs/0.quickstart-evm.md
  docs/0.quickstart-starknet.md
  docs/0.quickstart-tezos.md
Labels: documentation

#1038 Update curl spell for beta
  docs/0.quickstart-evm.md
  docs/0.quickstart-starknet.md
  docs/0.quickstart-tezos.md
  docs/1.getting-started/1.installation.md
  docs/_curl-spell.md
Labels: documentation

#1040 Fix `docs.yml` pipeline
  .github/workflows/docs.yml
  Makefile
Labels: ci/cd

#1043 Fix filtering events, default value for Meta.maxsize
  CHANGELOG.md
  Makefile
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  requirements.dev.txt
  requirements.txt
  src/demo_evm_uniswap/handlers/factory/pool_created.py
  src/demo_evm_uniswap/handlers/pool/swap.py
  src/demo_evm_uniswap/models/position.py
  src/dipdup/codegen/evm.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/starknet_events/fetcher.py
  src/dipdup/indexes/starknet_events/index.py
  src/dipdup/indexes/starknet_events/matcher.py
  src/dipdup/models/__init__.py
  src/dipdup/package.py
  src/dipdup/project.py
  src/dipdup/projects/demo_evm_uniswap/handlers/factory/pool_created.py.j2
  src/dipdup/projects/demo_evm_uniswap/handlers/pool/swap.py.j2
  src/dipdup/projects/demo_evm_uniswap/models/position.py.j2
Labels: bug

#1042 Improvements for Subsquid Cloud
  CHANGELOG.md
  Makefile
  docs/5.advanced/2.feature-flags.md
  docs/7.references/2.config.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  schema.json
  src/demo_blank/Makefile
  src/demo_blank/pyproject.toml
  src/demo_evm_events/Makefile
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/Makefile
  src/demo_evm_transactions/pyproject.toml
  src/demo_evm_uniswap/Makefile
  src/demo_evm_uniswap/pyproject.toml
  src/demo_starknet_events/Makefile
  src/demo_starknet_events/pyproject.toml
  src/demo_tezos_auction/Makefile
  src/demo_tezos_auction/pyproject.toml
  src/demo_tezos_big_maps/Makefile
  src/demo_tezos_big_maps/pyproject.toml
  src/demo_tezos_dao/Makefile
  src/demo_tezos_dao/pyproject.toml
  src/demo_tezos_dex/Makefile
  src/demo_tezos_dex/pyproject.toml
  src/demo_tezos_domains/Makefile
  src/demo_tezos_domains/pyproject.toml
  src/demo_tezos_etherlink/Makefile
  src/demo_tezos_etherlink/pyproject.toml
  src/demo_tezos_events/Makefile
  src/demo_tezos_events/pyproject.toml
  src/demo_tezos_factories/Makefile
  src/demo_tezos_factories/pyproject.toml
  src/demo_tezos_head/Makefile
  src/demo_tezos_head/pyproject.toml
  src/demo_tezos_nft_marketplace/Makefile
  src/demo_tezos_nft_marketplace/pyproject.toml
  src/demo_tezos_raw/Makefile
  src/demo_tezos_raw/pyproject.toml
  src/demo_tezos_token/Makefile
  src/demo_tezos_token/pyproject.toml
  src/demo_tezos_token_balances/Makefile
  src/demo_tezos_token_balances/pyproject.toml
  src/demo_tezos_token_transfers/Makefile
  src/demo_tezos_token_transfers/pyproject.toml
  src/dipdup/config/__init__.py
  src/dipdup/env.py
  src/dipdup/projects/base/Makefile.j2
  src/dipdup/projects/base/pyproject.toml.j2
  src/dipdup/sys.py
Labels: improvement

#1046 Update 8.0 release notes
  docs/9.release-notes/1.v8.0.md
Labels: documentation

#1047 Lazy `web3` imports
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/codegen/evm.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/indexes/evm.py
Labels: improvement
