Repository dipdup-io/dipdup, pull requests merged in 2024-04, with the labels that each got.

#862 Python 3.12 migration
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  docs/0.quickstart-evm.md
  docs/0.quickstart-tezos.md
  docs/1.getting-started/1.installation.md
  docs/14.contributing.md
  docs/6.deployment/2.docker.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/README.md
  src/demo_auction/pyproject.toml
  src/demo_big_maps/README.md
  src/demo_big_maps/pyproject.toml
  src/demo_blank/README.md
  src/demo_blank/pyproject.toml
  src/demo_dao/README.md
  src/demo_dao/pyproject.toml
  src/demo_dex/README.md
  src/demo_dex/pyproject.toml
  src/demo_domains/README.md
  src/demo_domains/pyproject.toml
  src/demo_etherlink/README.md
  src/demo_etherlink/pyproject.toml
  src/demo_events/README.md
  src/demo_events/pyproject.toml
  src/demo_evm_events/README.md
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/README.md
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/README.md
  src/demo_factories/pyproject.toml
  src/demo_head/README.md
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/README.md
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/README.md
  src/demo_raw/pyproject.toml
  src/demo_token/README.md
  src/demo_token/pyproject.toml
  src/demo_token_balances/README.md
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/README.md
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/README.md
  src/demo_uniswap/pyproject.toml
  src/dipdup/cli.py
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/install.py
  src/dipdup/projects/base/README.md.j2
  src/dipdup/projects/base/pyproject.toml.j2
  tests/profile_abi_decoding.py
Labels: improvement, breaking change

#988 Bump version 7.5.4
  CHANGELOG.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pyproject.toml
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
Labels: ci/cd, v7

#989 Fixed crash when database path is relative and nested
  CHANGELOG.md
  docs/9.release-notes/_7.5_changelog.md
  src/dipdup/config/__init__.py
Labels: bug

#995 Update badges in README
  README.md
Labels: documentation

#991 Improve processing `ValidationError`s
  src/dipdup/config/__init__.py
  src/dipdup/exceptions.py
  tests/test_config/test_custom_config.py
Labels: improvement, v8

#992 Allow using `evm.node` as index datasource
  CHANGELOG.md
  docs/2.indexes/_evm_subsquid.md
  docs/7.references/2.config.md
  schema.json
  src/dipdup/config/__init__.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/config/evm_subsquid_traces.py
  src/dipdup/config/evm_subsquid_transactions.py
  src/dipdup/context.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  tests/configs/demo_evm_events_node.yml
  tests/configs/demo_evm_transactions_node.yml
  tests/test_demos.py
Labels: improvement, v8

#997 Allow using `evm.node` as index datasource
  CHANGELOG.md
  docs/7.references/2.config.md
  schema.json
  src/dipdup/config/__init__.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_subsquid_events.py
  src/dipdup/config/evm_subsquid_traces.py
  src/dipdup/config/evm_subsquid_transactions.py
  src/dipdup/context.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  tests/configs/demo_evm_events_node.yml
  tests/configs/demo_evm_transactions_node.yml
Labels: improvement, v7

#999 Bump version 7.5.5
  CHANGELOG.md
  Makefile
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
Labels: ci/cd, v7

#1000 Fix oneshot logic
  src/dipdup/dipdup.py
Labels: bug

#1005 Bump core dependencies and document changes
  CHANGELOG.md
  docs/9.release-notes/1.v8.0.md
  docs/9.release-notes/_7.5_changelog.md
  docs/9.release-notes/_8.0_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
Labels: documentation, chore
