Repository dipdup-io/dipdup, pull requests merged in 2024-03, with the labels that each got.

#948 Allow bulk requests in Hasura Metadata API
  src/dipdup/hasura.py
Labels: feature, improvement

#947 More supported EVM networks
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#949 Enable API by default in compose, swarm envs
  src/demo_auction/configs/dipdup.compose.yaml
  src/demo_auction/configs/dipdup.swarm.yaml
  src/demo_big_maps/configs/dipdup.compose.yaml
  src/demo_big_maps/configs/dipdup.swarm.yaml
  src/demo_blank/configs/dipdup.compose.yaml
  src/demo_blank/configs/dipdup.swarm.yaml
  src/demo_dao/configs/dipdup.compose.yaml
  src/demo_dao/configs/dipdup.swarm.yaml
  src/demo_dex/configs/dipdup.compose.yaml
  src/demo_dex/configs/dipdup.swarm.yaml
  src/demo_domains/configs/dipdup.compose.yaml
  src/demo_domains/configs/dipdup.swarm.yaml
  src/demo_etherlink/configs/dipdup.compose.yaml
  src/demo_etherlink/configs/dipdup.swarm.yaml
  src/demo_events/configs/dipdup.compose.yaml
  src/demo_events/configs/dipdup.swarm.yaml
  src/demo_evm_events/configs/dipdup.compose.yaml
  src/demo_evm_events/configs/dipdup.swarm.yaml
  src/demo_evm_transactions/configs/dipdup.compose.yaml
  src/demo_evm_transactions/configs/dipdup.swarm.yaml
  src/demo_factories/configs/dipdup.compose.yaml
  src/demo_factories/configs/dipdup.swarm.yaml
  src/demo_head/configs/dipdup.compose.yaml
  src/demo_head/configs/dipdup.swarm.yaml
  src/demo_nft_marketplace/configs/dipdup.compose.yaml
  src/demo_nft_marketplace/configs/dipdup.swarm.yaml
  src/demo_raw/configs/dipdup.compose.yaml
  src/demo_raw/configs/dipdup.swarm.yaml
  src/demo_token/configs/dipdup.compose.yaml
  src/demo_token/configs/dipdup.swarm.yaml
  src/demo_token_balances/configs/dipdup.compose.yaml
  src/demo_token_balances/configs/dipdup.swarm.yaml
  src/demo_token_transfers/configs/dipdup.compose.yaml
  src/demo_token_transfers/configs/dipdup.swarm.yaml
  src/demo_uniswap/configs/dipdup.compose.yaml
  src/demo_uniswap/configs/dipdup.swarm.yaml
  src/dipdup/dipdup.py
  src/dipdup/projects/base/configs/dipdup.compose.yaml.j2
  src/dipdup/projects/base/configs/dipdup.swarm.yaml.j2
Labels: improvement

#951 Fixed processing node chain reorgs
  CHANGELOG.md
  pyproject.toml
  src/dipdup/context.py
  src/dipdup/datasources/__init__.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_traces/index.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_events/index.py
  src/dipdup/indexes/tezos_tzkt_head/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_token_balances/index.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
  src/dipdup/models/__init__.py
  src/dipdup/models/evm_subsquid.py
  src/dipdup/models/tezos_tzkt.py
  src/dipdup/test.py
Labels: bug

#950 Fixed memory leak when using node realtime subscriptions
  CHANGELOG.md
  Makefile
  pyproject.toml
  src/demo_evm_events/models/__init__.py
  src/demo_evm_transactions/models/__init__.py
  src/dipdup/context.py
  src/dipdup/datasources/__init__.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/index.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_events/matcher.py
  src/dipdup/indexes/evm_subsquid_traces/index.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_big_maps/index.py
  src/dipdup/indexes/tezos_tzkt_events/index.py
  src/dipdup/indexes/tezos_tzkt_head/index.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_token_balances/index.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/index.py
  src/dipdup/models/__init__.py
  src/dipdup/models/evm_subsquid.py
  src/dipdup/models/tezos_tzkt.py
  src/dipdup/performance.py
  src/dipdup/projects/demo_evm_events/models/__init__.py.j2
  src/dipdup/projects/demo_evm_transactions/models/__init__.py.j2
  src/dipdup/test.py
Labels: bug, improvement

#941 6.5 end-of-life release
  CHANGELOG.md
  demos/demo-big-maps/src/demo_big_maps/handlers/on_update_records.py
  demos/demo-events/src/demo_events/handlers/on_move_event.py
  demos/demo-events/src/demo_events/handlers/on_other_event.py
  demos/demo-events/src/demo_events/handlers/on_roll_event.py
  demos/demo-head/src/demo_head/handlers/on_mainnet_head.py
  docs/advanced/reindexing.md
  docs/book.css
  docs/book.toml
  docs/cli-reference.md
  docs/config/reference.md
  docs/deployment/database-engines.md
  docs/include/context-reference.md
  docs/mdbook-admonish.css
  docs/release-notes/4.0.0.md
  docs/theme/index.hbs
  poetry.lock
  pyproject.toml
  requirements.dev.txt
  requirements.pytezos.txt
  requirements.slim.txt
  requirements.txt
  src/dipdup/__init__.py
  src/dipdup/baking_bad.py
  src/dipdup/cli.py
  src/dipdup/codegen.py
  src/dipdup/config.py
  src/dipdup/datasources/datasource.py
  src/dipdup/datasources/metadata/enums.py
  src/dipdup/datasources/subscription.py
  src/dipdup/datasources/tzkt/datasource.py
  src/dipdup/exceptions.py
  src/dipdup/fetcher.py
  src/dipdup/install.py
  src/dipdup/project.py
  tests/replays/04e415fc3665e1fc07720c2d6da9260318c9e62f04b11037745f1be259ebad25
  tests/replays/29cb9e5c322a4931bcbdea8a8e763de55fb8374bdfb0e0d9f96d402725498625
  tests/replays/330ac9153e658b51309aaabe5a0e842426557c66313925b4707a1fc7fcd1664d
  tests/replays/532989662bb554c096733afe371899b76cecbac2fec893e04fee550db8596229
  tests/replays/5aab67735a2426013d90038c4e3c293f5134b579006e774b3797b094441530fc
  tests/replays/743ea1ba4b48fa3a079becc24a518e412bc65184fc15bfabd02a4bb903485326
  tests/replays/7d4a99edf5845445bbeb894ad34b063c985ca061ffed162093721c0032210e31
  tests/replays/818b0c3c7d108909296fd0b45baa565f4348e85fa914115e1b38ae5f38832f5a
  tests/replays/8cc1672fe6ba88cdbf637f13c5e5e1dd6768f138e73b6f9d888fcc624437c824
  tests/replays/a37a81d76f0a08b04bf3898d9a3de2ea92d0174dd78234f6e8088d070b454f29
  tests/replays/a4fe8f2c6550cee778a283df4c2bd72f5a13703abc1b39ecd97c47904905a9a8
  tests/replays/ac90e58a39f73ec497627296ed039e77e2000acdd5d7e3a5fe783eadf1da35e0
  tests/replays/b3dae9063fd2b403cd8dc6abc0947bf971c59c433bd3f364130d7b8cda2728fd
  tests/replays/c68713e7be41a62c38bf9da30f21055180f268728bbad9933da06365396ca227
  tests/replays/ca25ab82dbe3de6916236f01aa756e697da5ca9376a4ac964da1db24f928bf4d
  tests/replays/e08ce8d29b7f382a7cd3b55fef358f0a573e2be46b49946351e2f897d7ecd25a
  tests/replays/e4ee41cd9354130632c68b0164fc79568147c685dd74ac7e62c157ba8dfa7fac
  tests/replays/ea303108b7f5de0750ffa442a5a469d621628e950646db94b15442241134032e
  tests/replays/f96d627b969c8163724f64784938421e44c928d11cf8114f65c3cfa5a82bd003
  tests/test_introspection.py
  tests/test_utils.py
Labels: bug

#956 Bump version 7.5.0
  CHANGELOG.md
  docs/5.advanced/6.evm-networks.md
  docs/7.references/2.config.md
  docs/9.release-notes/1.v7.5.md
  docs/9.release-notes/2.v7.4.md
  docs/9.release-notes/3.v7.3.md
  docs/9.release-notes/4.v7.2.md
  docs/9.release-notes/5.v7.1.md
  docs/9.release-notes/6.v6.5.md
  docs/9.release-notes/6.v7.0.md
  docs/9.release-notes/7.history.md
  docs/9.release-notes/_footer.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  schema.json
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/codegen/evm_subsquid.py
  src/dipdup/config/__init__.py
  src/dipdup/datasources/abi_etherscan.py
  src/dipdup/datasources/evm_node.py
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/exceptions.py
  src/dipdup/hasura.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  src/dipdup/models/evm_node.py
Labels: documentation, improvement

#959 Update changelog, bump eth-abi and pysignalr
  CHANGELOG.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
Labels: chore

#961 Add Karak
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#960 Fix RPC URLs on EVM networks page
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#962 Add Hokum to EVM networks page
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#958 Refactor EVM node synchronization
  CHANGELOG.md
  Makefile
  src/dipdup/datasources/evm_node.py
  src/dipdup/fetcher.py
  src/dipdup/indexes/evm_node.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid_events/fetcher.py
  src/dipdup/indexes/evm_subsquid_events/index.py
  src/dipdup/indexes/evm_subsquid_traces/fetcher.py
  src/dipdup/indexes/evm_subsquid_transactions/fetcher.py
  src/dipdup/indexes/evm_subsquid_transactions/index.py
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/indexes/tezos_tzkt_big_maps/fetcher.py
  src/dipdup/indexes/tezos_tzkt_events/fetcher.py
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/indexes/tezos_tzkt_token_transfers/fetcher.py
  src/dipdup/models/evm_node.py
Labels: chore, improvement

#963 Bump version 7.5.1
  CHANGELOG.md
  docs/9.release-notes/1.v7.5.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/report.py
  src/dipdup/sentry.py
  tests/test_introspection.py
Labels: ci/cd

#964 Add subsquid for Blast and Scroll
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#965 Minor docs fixes, merged release changelogs
  CHANGELOG.md
  docs/5.advanced/6.evm-networks.md
  docs/9.release-notes/1.v7.5.md
  docs/9.release-notes/2.v7.4.md
  docs/9.release-notes/3.v7.3.md
  docs/9.release-notes/4.v7.2.md
  docs/9.release-notes/5.v7.1.md
  scripts/docs.py
Labels: documentation

#969 Update EVM Networks page
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#968 Fix updating `dipdup_head` table when head block is received
  CHANGELOG.md
  src/dipdup/datasources/evm_node.py
Labels: bug

#970 Bump version 7.5.2
  CHANGELOG.md
  Makefile
  docs/9.release-notes/1.v7.5.md
  docs/9.release-notes/2.v7.4.md
  docs/9.release-notes/3.v7.3.md
  docs/9.release-notes/4.v7.2.md
  docs/9.release-notes/5.v7.1.md
  docs/9.release-notes/_7.0_changelog.md
  docs/9.release-notes/_7.1_changelog.md
  docs/9.release-notes/_7.2_changelog.md
  docs/9.release-notes/_7.3_changelog.md
  docs/9.release-notes/_7.4_changelog.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  projects
  pyproject.toml
  requirements.dev.txt
  requirements.txt
  scripts/demos.py
  scripts/docs.py
  src/demo_auction/pyproject.toml
  src/demo_big_maps/handlers/on_update_records.py
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/handlers/on_fa12_tez_to_token.py
  src/demo_dex/handlers/on_fa12_token_to_tez.py
  src/demo_dex/handlers/on_fa2_tez_to_token.py
  src/demo_dex/handlers/on_fa2_token_to_tez.py
  src/demo_dex/pyproject.toml
  src/demo_domains/handlers/on_update_records.py
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/indexes/tezos_tzkt.py
  src/dipdup/projects/demo_big_maps/handlers/on_update_records.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa12_tez_to_token.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa12_token_to_tez.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa2_tez_to_token.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa2_token_to_tez.py.j2
  src/dipdup/projects/demo_domains/handlers/on_update_records.py.j2
  templates
Labels: ci/cd

#974 Add Mode
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#972 Astar and Bitgert test results
  docs/5.advanced/6.evm-networks.md
Labels: documentation

#975 Update Subsquid request and response models
  src/dipdup/datasources/evm_subsquid.py
  src/dipdup/indexes/evm_subsquid.py
  src/dipdup/models/evm_subsquid.py
  src/dipdup/utils.py
Labels: chore

#973 Add source code links to Demos page
  docs/8.examples/_demos_table.md
  scripts/docs.py
Labels: documentation

#976 Fixed missing operations when handler pattern contains item without entrypoint
  CHANGELOG.md
  docs/15.thanks.md
  src/dipdup/codegen/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/indexes/tezos_tzkt_operations/index.py
  src/dipdup/indexes/tezos_tzkt_operations/matcher.py
  src/dipdup/models/tezos_tzkt.py
  tests/configs/demo_dex.yml
  tests/test_demos.py
Labels: bug, community

#977 Bump version 7.5.3
  CHANGELOG.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_7.5_changelog.md
  pdm.lock
  pyproject.toml
  requirements.dev.txt
  src/demo_auction/pyproject.toml
  src/demo_big_maps/pyproject.toml
  src/demo_blank/pyproject.toml
  src/demo_dao/pyproject.toml
  src/demo_dex/handlers/on_fa12_tez_to_token.py
  src/demo_dex/handlers/on_fa12_token_to_tez.py
  src/demo_dex/handlers/on_fa2_tez_to_token.py
  src/demo_dex/handlers/on_fa2_token_to_tez.py
  src/demo_dex/pyproject.toml
  src/demo_domains/pyproject.toml
  src/demo_etherlink/pyproject.toml
  src/demo_events/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_factories/pyproject.toml
  src/demo_head/pyproject.toml
  src/demo_nft_marketplace/pyproject.toml
  src/demo_raw/pyproject.toml
  src/demo_token/pyproject.toml
  src/demo_token_balances/pyproject.toml
  src/demo_token_transfers/pyproject.toml
  src/demo_uniswap/pyproject.toml
  src/dipdup/indexes/tezos_tzkt_operations/fetcher.py
  src/dipdup/projects/demo_dex/handlers/on_fa12_tez_to_token.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa12_token_to_tez.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa2_tez_to_token.py.j2
  src/dipdup/projects/demo_dex/handlers/on_fa2_token_to_tez.py.j2
Labels: ci/cd
