Repository dipdup-io/dipdup, pull requests merged in 2025-05, with the labels that each got.

#1249 Fix `make image` command and default workdir
  CHANGELOG.md
  src/demo_blank/Makefile
  src/demo_blank/deploy/Dockerfile
  src/demo_evm_events/Makefile
  src/demo_evm_events/deploy/Dockerfile
  src/demo_evm_transactions/Makefile
  src/demo_evm_transactions/deploy/Dockerfile
  src/demo_evm_uniswap/Makefile
  src/demo_evm_uniswap/deploy/Dockerfile
  src/demo_starknet_events/Makefile
  src/demo_starknet_events/deploy/Dockerfile
  src/demo_substrate_events/Makefile
  src/demo_substrate_events/deploy/Dockerfile
  src/demo_tezos_auction/Makefile
  src/demo_tezos_auction/deploy/Dockerfile
  src/demo_tezos_dao/Makefile
  src/demo_tezos_dao/deploy/Dockerfile
  src/demo_tezos_dex/Makefile
  src/demo_tezos_dex/deploy/Dockerfile
  src/demo_tezos_domains/Makefile
  src/demo_tezos_domains/deploy/Dockerfile
  src/demo_tezos_events/Makefile
  src/demo_tezos_events/deploy/Dockerfile
  src/demo_tezos_factories/Makefile
  src/demo_tezos_factories/deploy/Dockerfile
  src/demo_tezos_head/Makefile
  src/demo_tezos_head/deploy/Dockerfile
  src/demo_tezos_nft_marketplace/Makefile
  src/demo_tezos_nft_marketplace/deploy/Dockerfile
  src/demo_tezos_raw/Makefile
  src/demo_tezos_raw/deploy/Dockerfile
  src/demo_tezos_token/Makefile
  src/demo_tezos_token/deploy/Dockerfile
  src/demo_tezos_token_balances/Makefile
  src/demo_tezos_token_balances/deploy/Dockerfile
  src/demo_tezos_token_transfers/Makefile
  src/demo_tezos_token_transfers/deploy/Dockerfile
  src/dipdup/projects/base/Makefile.j2
  src/dipdup/projects/base/deploy/Dockerfile.j2
Labels: bug

#1245 Codegen refactoring
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/codegen/substrate.py
  src/dipdup/dipdup.py
Labels: bug

#1251 Fix loading ABIs with no ABI datasources configured
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  requirements.txt
  src/dipdup/codegen/__init__.py
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/datasources/__init__.py
  uv.lock
Labels: bug

#1253 Watchdog service
  CHANGELOG.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/7.references/4.models.md
  docs/8.examples/_demos_table.md
  docs/9.release-notes/_8.0_changelog.md
  docs/config.rst
  docs/models.rst
  schemas/dipdup-3.0.json
  scripts/docs.py
  src/dipdup/config/__init__.py
  src/dipdup/config/tezos_big_maps.py
  src/dipdup/context.py
  src/dipdup/datasources/tezos_tzkt.py
  src/dipdup/dipdup.py
  src/dipdup/exceptions.py
  src/dipdup/indexes/tezos_big_maps/index.py
  src/dipdup/models/__init__.py
  src/dipdup/transactions.py
  src/dipdup/watchdog.py
  tests/test_hasura.py
Labels: improvement

#1255 Fixed Substrate Node Event Index [2]
  src/dipdup/datasources/substrate_node.py
  src/dipdup/indexes/substrate_events/fetcher.py
Labels: bug

#1259 8.4 release notes, http URL and config fixes
  CHANGELOG.md
  docs/5.advanced/2.environment-variables.md
  docs/5.advanced/6.sqd-cloud.md
  docs/7.references/2.config.md
  docs/9.release-notes/1.v8.4.md
  docs/9.release-notes/10.v7.1.md
  docs/9.release-notes/11.v7.0.md
  docs/9.release-notes/2.v8.3.md
  docs/9.release-notes/3.v8.2.md
  docs/9.release-notes/4.v8.1.md
  docs/9.release-notes/5.v8.0.md
  docs/9.release-notes/6.v7.5.md
  docs/9.release-notes/7.v7.4.md
  docs/9.release-notes/8.v7.3.md
  docs/9.release-notes/9.v7.2.md
  docs/9.release-notes/_8.4_changelog.md
  docs/config.rst
  requirements.txt
  schemas/dipdup-3.0.json
  src/dipdup/config/__init__.py
  src/dipdup/datasources/_subsquid.py
  src/dipdup/dipdup.py
  src/dipdup/http.py
  src/dipdup/watchdog.py
  tests/test_http.py
  uv.lock
Labels: bug, documentation
