Repository dipdup-io/dipdup, pull requests merged in 2025-01, with the labels that each got.

#1180 fix request_id
  src/dipdup/datasources/__init__.py
Labels: bug, community

#1181 [Fix] Allow starknet contract addresses starting with '0x0'
  src/dipdup/config/starknet.py
  tests/configs/demo_starknet_events.yml
Labels: community, improvement

#1182 Fix parsing EVM tuples
  CHANGELOG.md
  docs/16.thanks.md
  docs/7.references/2.config.md
  docs/9.release-notes/_8.0_changelog.md
  docs/config.rst
  src/dipdup/abi/evm.py
  src/dipdup/indexes/evm_events/matcher.py
  src/dipdup/indexes/evm_transactions/matcher.py
  src/dipdup/utils.py
Labels: bug

#1189 Fix release workflow and changelog
  .github/workflows/release.yml
  CHANGELOG.md
  docs/9.release-notes/_8.2_changelog.md
Labels: ci/cd

#1190 Another release workflow fix
  .github/workflows/release.yml
Labels: ci/cd

#1191 Disable cache in setup-python step
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
Labels: ci/cd

#1192 Publish docs on tags, fix version in quickstart
  .github/workflows/docs.yml
  docs/0.quickstart-substrate.md
  src/dipdup/install.py
Labels: documentation, ci/cd

#1193 Fix cloning frontend repo
  .github/workflows/docs.yml
Labels: ci/cd

#1196 Update tortoise-orm to 0.24.0
  CHANGELOG.md
  pyproject.toml
  requirements.txt
  src/dipdup/fields.py
  src/dipdup/models/__init__.py
  uv.lock
Labels: improvement

#1200 DipDup package structure validation
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/cli.py
  src/dipdup/package.py
Labels: improvement

#1199 Fix parsing nested structures in response
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/models/substrate.py
  src/dipdup/runtimes.py
  tests/test_datasources/test_substrate.py
Labels: bug

#1203 Fix sqd preprocessing, namespace package checks
  scripts/demos.py
  src/demo_blank/pyproject.toml
  src/demo_evm_events/pyproject.toml
  src/demo_evm_transactions/pyproject.toml
  src/demo_evm_uniswap/pyproject.toml
  src/demo_starknet_events/pyproject.toml
  src/demo_substrate_events/pyproject.toml
  src/demo_tezos_auction/pyproject.toml
  src/demo_tezos_dao/pyproject.toml
  src/demo_tezos_dex/pyproject.toml
  src/demo_tezos_domains/pyproject.toml
  src/demo_tezos_events/pyproject.toml
  src/demo_tezos_factories/pyproject.toml
  src/demo_tezos_head/pyproject.toml
  src/demo_tezos_nft_marketplace/pyproject.toml
  src/demo_tezos_raw/pyproject.toml
  src/demo_tezos_token/pyproject.toml
  src/demo_tezos_token_balances/pyproject.toml
  src/demo_tezos_token_transfers/pyproject.toml
  src/dipdup/package.py
  src/dipdup/projects/base/pyproject.toml.j2
  src/dipdup/runtimes.py
  tests/test_datasources/test_substrate.py
Labels: bug

#1204 Fix help message on `CallbackError` reporting `batch` handler
  CHANGELOG.md
  src/dipdup/cli.py
Labels: bug

#1207 Add substrate helper, fix codegen crash
  src/dipdup/codegen/substrate.py
  src/dipdup/runtimes.py
  tests/test_datasources/test_substrate.py
Labels: chore
