Repository dipdup-io/dipdup, pull requests merged in 2025-02, with the labels that each got.

#1208 Fixed data parsing for `__kind` junctions with multiple keys
  CHANGELOG.md
  src/dipdup/runtimes.py
  tests/test_datasources/test_substrate.py
Labels: bug

#1202 Abi fetching through StarknetNode datasource
  CHANGELOG.md
  src/demo_starknet_events/abi/stark_usdt/cairo_abi.json
  src/dipdup/abi/cairo.py
  src/dipdup/codegen/evm.py
  src/dipdup/codegen/starknet.py
  src/dipdup/datasources/__init__.py
  src/dipdup/datasources/evm_etherscan.py
  src/dipdup/datasources/starknet_node.py
  src/dipdup/datasources/substrate_subscan.py
  src/dipdup/fetcher.py
  src/dipdup/projects/demo_starknet_events/abi/stark_usdt/cairo_abi.json.j2
Labels: feature, community

#1212 Handle Starknet events keys/data correctly
  src/dipdup/abi/cairo.py
  src/dipdup/codegen/evm.py
Labels: improvement

#1213 Dirty solution for timestamp and transaction index fetching
  src/dipdup/datasources/starknet_node.py
  src/dipdup/indexes/starknet_events/fetcher.py
Labels: community, improvement

#1219 Fix double Quickstart page
  docs/0.quickstart-substrate.md
Labels: documentation

#1217 Universal config generator
  CHANGELOG.md
  docs/9.release-notes/_8.0_changelog.md
  requirements.txt
  schemas/dipdup-3.0.json
  src/dipdup/_survey.py
  src/dipdup/cli.py
  src/dipdup/config/__init__.py
  src/dipdup/config/_mixin.py
  src/dipdup/config/coinbase.py
  src/dipdup/config/evm.py
  src/dipdup/config/evm_etherscan.py
  src/dipdup/config/evm_events.py
  src/dipdup/config/evm_node.py
  src/dipdup/config/evm_subsquid.py
  src/dipdup/config/evm_transactions.py
  src/dipdup/config/http.py
  src/dipdup/config/ipfs.py
  src/dipdup/config/starknet.py
  src/dipdup/config/starknet_events.py
  src/dipdup/config/starknet_node.py
  src/dipdup/config/starknet_subsquid.py
  src/dipdup/config/substrate_events.py
  src/dipdup/config/substrate_node.py
  src/dipdup/config/substrate_subscan.py
  src/dipdup/config/substrate_subsquid.py
  src/dipdup/config/tezos.py
  src/dipdup/config/tezos_big_maps.py
  src/dipdup/config/tezos_events.py
  src/dipdup/config/tezos_head.py
  src/dipdup/config/tezos_operations.py
  src/dipdup/config/tezos_token_balances.py
  src/dipdup/config/tezos_token_transfers.py
  src/dipdup/config/tezos_tzkt.py
  src/dipdup/config/tzip_metadata.py
  src/dipdup/datasources/coinbase.py
  src/dipdup/project.py
  src/dipdup/yaml.py
  uv.lock
Labels: feature

#1220 Monad network support
  CHANGELOG.md
  docs/1.getting-started/7.datasources.md
  docs/10.supported-networks/31.mode.md
  docs/10.supported-networks/32.monad.md
  docs/10.supported-networks/33.moonbeam.md
  docs/10.supported-networks/34.neon.md
  docs/10.supported-networks/35.opbnb.md
  docs/10.supported-networks/36.optimism.md
  docs/10.supported-networks/37.peaq.md
  docs/10.supported-networks/38.polygon.md
  docs/10.supported-networks/39.prom.md
  docs/10.supported-networks/40.scroll.md
  docs/10.supported-networks/41.shibarium.md
  docs/10.supported-networks/42.shibuya.md
  docs/10.supported-networks/43.shiden.md
  docs/10.supported-networks/44.scale.md
  docs/10.supported-networks/45.sonic.md
  docs/10.supported-networks/46.taiko.md
  docs/10.supported-networks/47.tanssi.md
  docs/10.supported-networks/48.x1.md
  docs/10.supported-networks/49.x-layer.md
  docs/10.supported-networks/50.zksync.md
  docs/10.supported-networks/51.zora.md
  docs/2.indexes/_starknet.md
  docs/2.indexes/_substrate.md
  docs/3.datasources/10.substrate_subsquid.md
  docs/3.datasources/11.tezos_tzkt.md
  docs/3.datasources/12.tzip_metadata.md
  docs/3.datasources/13.coinbase.md
  docs/3.datasources/14.ipfs.md
  docs/3.datasources/15.http.md
  docs/3.datasources/3.evm_etherscan.md
  docs/3.datasources/4.evm_blockvision.md
  docs/3.datasources/5.evm_sourcify.md
  docs/3.datasources/6.starknet_subsquid.md
  docs/3.datasources/7.starknet_node.md
  docs/3.datasources/8.substrate_node.md
  docs/3.datasources/9.substrate_subscan.md
  docs/7.references/2.config.md
  docs/9.release-notes/3.v8.0.md
  docs/9.release-notes/_8.0_changelog.md
  schemas/dipdup-3.0.json
  src/dipdup/codegen/evm.py
  src/dipdup/config/__init__.py
  src/dipdup/config/evm.py
  src/dipdup/config/evm_blockvision.py
  src/dipdup/config/evm_sourcify.py
  src/dipdup/context.py
  src/dipdup/datasources/__init__.py
  src/dipdup/datasources/evm_blockvision.py
  src/dipdup/datasources/evm_sourcify.py
  src/dipdup/indexes/evm_node.py
Labels: documentation, feature

#1224 Add Somnia Testnet
  docs/1.getting-started/5.database.md
  docs/1.getting-started/7.datasources.md
  docs/10.supported-networks/0.overview.md
  docs/10.supported-networks/23.hokum.md
  docs/10.supported-networks/24.kakarot.md
  docs/10.supported-networks/25.karak.md
  docs/10.supported-networks/39.prom.md
  docs/10.supported-networks/42.shibuya.md
  docs/10.supported-networks/44.somnia.md
  docs/10.supported-networks/45.scale.md
  docs/10.supported-networks/46.sonic.md
  docs/10.supported-networks/46.taiko.md
  docs/10.supported-networks/47.taiko.md
  docs/10.supported-networks/48.tanssi.md
  docs/10.supported-networks/49.x1.md
  docs/10.supported-networks/50.x-layer.md
  docs/10.supported-networks/51.zksync.md
  docs/10.supported-networks/52.zora.md
  docs/10.supported-networks/9.bob.md
  docs/3.datasources/1.evm_subsquid.md
  docs/3.datasources/10.substrate_subsquid.md
  docs/3.datasources/11.tezos_tzkt.md
  docs/3.datasources/12.tzip_metadata.md
  docs/3.datasources/2.evm_node.md
  docs/3.datasources/3.evm_etherscan.md
  docs/3.datasources/4.evm_blockvision.md
  docs/3.datasources/5.evm_sourcify.md
  docs/3.datasources/6.starknet_subsquid.md
  docs/3.datasources/7.starknet_node.md
  docs/3.datasources/8.substrate_node.md
  docs/3.datasources/9.substrate_subscan.md
  docs/3.datasources/_subsquid_banner.md
  docs/7.references/2.config.md
  docs/7.references/3.context.md
  docs/7.references/4.models.md
Labels: documentation
