Repository dipdup-io/dipdup, pull requests merged in 2025-04, with the labels that each got.

#1233 8.3 release notes and docs
  CHANGELOG.md
  docs/1.getting-started/4.package.md
  docs/5.advanced/7.mcp.md
  docs/9.release-notes/1.v8.3.md
  docs/9.release-notes/_8.3_changelog.md
Labels: documentation

#1231 Add ruff linting and formatting to demo rendering
  CHANGELOG.md
  Makefile
  docs/7.references/1.cli.md
  docs/9.release-notes/_8.3_changelog.md
  pyproject.toml
  requirements.txt
  src/demo_substrate_events/abi/assethub/v601.json
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/dipdup.py
  src/dipdup/env.py
  src/dipdup/package.py
  tests/test_demos.py
  uv.lock
Labels: documentation, feature

#1238 Fix `new` command using incorrect template
  CHANGELOG.md
  src/dipdup/cli.py
Labels: bug

#1239 GHA workflow optimizations
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ci/cd

#1240 Set `init --base` flag by defaault
  CHANGELOG.md
  Makefile
  docs/1.getting-started/1.installation.md
  docs/1.getting-started/4.package.md
  docs/12.faq.md
  docs/5.advanced/2.environment-variables.md
  docs/7.references/1.cli.md
  docs/9.release-notes/1.v8.3.md
  docs/9.release-notes/_8.0_changelog.md
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/dipdup.py
  src/dipdup/env.py
Labels: improvement

#1241 Add `ctx.api` and `ctx.call_api` to MCP context
  CHANGELOG.md
  docs/5.advanced/7.mcp.md
  src/dipdup/cli.py
  src/dipdup/context.py
  src/dipdup/mcp.py
Labels: improvement

#1243 Update vscode config examples
  docs/5.advanced/7.mcp.md
Labels: documentation

#1244 Fix bugs in CLI and codegen
  CHANGELOG.md
  docs/7.references/1.cli.md
  docs/9.release-notes/_8.0_changelog.md
  pyproject.toml
  requirements.txt
  src/dipdup/cli.py
  src/dipdup/codegen/__init__.py
  src/dipdup/context.py
  src/dipdup/dipdup.py
  src/dipdup/project.py
  uv.lock
Labels: bug

#1246 Bump tortoise-orm
  pyproject.toml
  requirements.txt
  uv.lock
Labels: chore

#1247 Bump `pysignalr`
  requirements.txt
  uv.lock
Labels: chore
